<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Seeder;

/**
 * Seeds the full set of base languages that the app advertises in
 * android/app/src/main/res/xml/locale_config.xml (Google Play's supported
 * languages). Regional variants (en-GB, es-MX, pt-BR, zh-CN, …) fall back to
 * their base language at runtime, so only the ~71 unique base languages are
 * stored here. UI string content is generated by `php artisan translate:all`.
 *
 * Idempotent: existing rows are updated, new ones created. Does NOT change the
 * default language (ar) or deactivate anything.
 */
class AllLanguagesSeeder extends Seeder
{
    /** code => [name, native, rtl] */
    private array $languages = [
        'ar'  => ['Arabic', 'العربية', true],
        'en'  => ['English', 'English', false],
        'af'  => ['Afrikaans', 'Afrikaans', false],
        'am'  => ['Amharic', 'አማርኛ', false],
        'az'  => ['Azerbaijani', 'Azərbaycan', false],
        'be'  => ['Belarusian', 'Беларуская', false],
        'bg'  => ['Bulgarian', 'Български', false],
        'bn'  => ['Bengali', 'বাংলা', false],
        'ca'  => ['Catalan', 'Català', false],
        'cs'  => ['Czech', 'Čeština', false],
        'da'  => ['Danish', 'Dansk', false],
        'de'  => ['German', 'Deutsch', false],
        'el'  => ['Greek', 'Ελληνικά', false],
        'es'  => ['Spanish', 'Español', false],
        'et'  => ['Estonian', 'Eesti', false],
        'eu'  => ['Basque', 'Euskara', false],
        'fa'  => ['Persian', 'فارسی', true],
        'fi'  => ['Finnish', 'Suomi', false],
        'fil' => ['Filipino', 'Filipino', false],
        'fr'  => ['French', 'Français', false],
        'gl'  => ['Galician', 'Galego', false],
        'gu'  => ['Gujarati', 'ગુજરાતી', false],
        'he'  => ['Hebrew', 'עברית', true],
        'hi'  => ['Hindi', 'हिन्दी', false],
        'hr'  => ['Croatian', 'Hrvatski', false],
        'hu'  => ['Hungarian', 'Magyar', false],
        'hy'  => ['Armenian', 'Հայերեն', false],
        'id'  => ['Indonesian', 'Bahasa Indonesia', false],
        'is'  => ['Icelandic', 'Íslenska', false],
        'it'  => ['Italian', 'Italiano', false],
        'ja'  => ['Japanese', '日本語', false],
        'ka'  => ['Georgian', 'ქართული', false],
        'kk'  => ['Kazakh', 'Қазақ', false],
        'km'  => ['Khmer', 'ខ្មែរ', false],
        'kn'  => ['Kannada', 'ಕನ್ನಡ', false],
        'ko'  => ['Korean', '한국어', false],
        'ku'  => ['Kurdish', 'کوردی', true],
        'ky'  => ['Kyrgyz', 'Кыргызча', false],
        'lo'  => ['Lao', 'ລາວ', false],
        'lt'  => ['Lithuanian', 'Lietuvių', false],
        'lv'  => ['Latvian', 'Latviešu', false],
        'mk'  => ['Macedonian', 'Македонски', false],
        'ml'  => ['Malayalam', 'മലയാളം', false],
        'mn'  => ['Mongolian', 'Монгол', false],
        'mr'  => ['Marathi', 'मराठी', false],
        'ms'  => ['Malay', 'Bahasa Melayu', false],
        'my'  => ['Burmese', 'မြန်မာ', false],
        'ne'  => ['Nepali', 'नेपाली', false],
        'nl'  => ['Dutch', 'Nederlands', false],
        'no'  => ['Norwegian', 'Norsk', false],
        'pa'  => ['Punjabi', 'ਪੰਜਾਬੀ', false],
        'pl'  => ['Polish', 'Polski', false],
        'pt'  => ['Portuguese', 'Português', false],
        'rm'  => ['Romansh', 'Rumantsch', false],
        'ro'  => ['Romanian', 'Română', false],
        'ru'  => ['Russian', 'Русский', false],
        'si'  => ['Sinhala', 'සිංහල', false],
        'sk'  => ['Slovak', 'Slovenčina', false],
        'sl'  => ['Slovenian', 'Slovenščina', false],
        'sq'  => ['Albanian', 'Shqip', false],
        'sr'  => ['Serbian', 'Српски', false],
        'sv'  => ['Swedish', 'Svenska', false],
        'sw'  => ['Swahili', 'Kiswahili', false],
        'ta'  => ['Tamil', 'தமிழ்', false],
        'te'  => ['Telugu', 'తెలుగు', false],
        'th'  => ['Thai', 'ไทย', false],
        'tr'  => ['Turkish', 'Türkçe', false],
        'uk'  => ['Ukrainian', 'Українська', false],
        'ur'  => ['Urdu', 'اردو', true],
        'vi'  => ['Vietnamese', 'Tiếng Việt', false],
        'zh'  => ['Chinese', '中文', false],
        'zu'  => ['Zulu', 'isiZulu', false],
    ];

    public function run(): void
    {
        $sortOrder = 1;
        $created = 0;
        $updated = 0;

        foreach ($this->languages as $code => [$name, $native, $rtl]) {
            $existing = Language::where('code', $code)->first();

            Language::updateOrCreate(
                ['code' => $code],
                [
                    'name'        => $name,
                    'native_name' => $native,
                    'direction'   => $rtl ? 'rtl' : 'ltr',
                    'is_active'   => true,
                    // Preserve existing default flag; only ar is default by convention.
                    'is_default'  => $existing?->is_default ?? ($code === 'ar'),
                    'sort_order'  => $existing?->sort_order ?? $sortOrder,
                ]
            );

            $existing ? $updated++ : $created++;
            $sortOrder++;
        }

        Language::clearCache();

        $this->command->info("Languages seeded: {$created} created, {$updated} updated, " . count($this->languages) . ' total.');
        $this->command->warn('Next: php artisan translate:all          (generates UI strings via AI for every language)');
        $this->command->warn('Then: php artisan translations:export-bundle  (writes offline JSON bundle for the app)');
    }
}
