<?php

namespace Database\Seeders;

use App\Models\cities;
use App\Models\city;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            ['id' => '1', 'countries_id' => '1', 'name' => 'خان يونس'],
            ['id' => '2', 'countries_id' => '1', 'name' => 'رفح'],
            ['id' => '3', 'countries_id' => '1', 'name' => 'رام الله'],
            ['id' => '4', 'countries_id' => '1', 'name' => 'الخليل'],
            ['id' => '5', 'countries_id' => '1', 'name' => 'بيت لحم'],
            ['id' => '6', 'countries_id' => '1', 'name' => 'نابلس'],
            ['id' => '7', 'countries_id' => '1', 'name' => 'جنين'],
            ['id' => '8', 'countries_id' => '1', 'name' => 'سلفيت'],
            ['id' => '9', 'countries_id' => '1', 'name' => 'عسقلان'],
            ['id' => '10', 'countries_id' => '1', 'name' => 'بئر السبع'],
            ['id' => '11', 'countries_id' => '1', 'name' => 'طبريا'],
            ['id' => '12', 'countries_id' => '1', 'name' => 'الناصرة'],
            ['id' => '344', 'countries_id' => '1', 'name' => 'صفد'],
            ['id' => '13', 'countries_id' => '1', 'name' => 'بيسان'],
            ['id' => '14', 'countries_id' => '1', 'name' => 'اللد'],
            ['id' => '15', 'countries_id' => '1', 'name' => 'الرملة'],
            ['id' => '16', 'countries_id' => '1', 'name' => 'طولكرم'],
            ['id' => '17', 'countries_id' => '1', 'name' => 'قلقيلية'],
            ['id' => '18', 'countries_id' => '1', 'name' => 'عكا'],
            ['id' => '19', 'countries_id' => '1', 'name' => 'حيفا'],
            ['id' => '20', 'countries_id' => '1', 'name' => 'يافا'],
            ['id' => '22', 'countries_id' => '1', 'name' => 'أريحا'],
            ['id' => '23', 'countries_id' => '2', 'name' => 'القاهرة'],
            ['id' => '24', 'countries_id' => '2', 'name' => 'الإسكندرية'],
            ['id' => '25', 'countries_id' => '2', 'name' => 'الجيزة'],
            ['id' => '26', 'countries_id' => '2', 'name' => 'الأسكندرية'],
            ['id' => '27', 'countries_id' => '2', 'name' => 'الشرقية'],
            ['id' => '28', 'countries_id' => '2', 'name' => 'المنوفية'],
            ['id' => '29', 'countries_id' => '2', 'name' => 'القليوبية'],
            ['id' => '30', 'countries_id' => '2', 'name' => 'الدقهلية'],
            ['id' => '31', 'countries_id' => '2', 'name' => 'كفر الشيخ'],
            ['id' => '32', 'countries_id' => '2', 'name' => 'الغربية'],
            ['id' => '33', 'countries_id' => '2', 'name' => 'المنيا'],
            ['id' => '34', 'countries_id' => '2', 'name' => 'البحيرة'],
            ['id' => '35', 'countries_id' => '2', 'name' => 'الفيوم'],
            ['id' => '36', 'countries_id' => '2', 'name' => 'الإسماعيلية'],
            ['id' => '37', 'countries_id' => '2', 'name' => 'أسوان'],
            ['id' => '38', 'countries_id' => '2', 'name' => 'أسيوط'],
            ['id' => '39', 'countries_id' => '2', 'name' => 'بني سويف'],
            ['id' => '40', 'countries_id' => '2', 'name' => 'بورسعيد'],
            ['id' => '41', 'countries_id' => '2', 'name' => 'دمياط'],
            ['id' => '42', 'countries_id' => '2', 'name' => 'السويس'],
            ['id' => '43', 'countries_id' => '2', 'name' => 'الأقصر'],
            ['id' => '44', 'countries_id' => '2', 'name' => 'البحر الأحمر'],
            ['id' => '45', 'countries_id' => '2', 'name' => 'الوادي الجديد'],
            ['id' => '46', 'countries_id' => '2', 'name' => 'سوهاج'],
            ['id' => '47', 'countries_id' => '2', 'name' => 'قنا'],
            ['id' => '48', 'countries_id' => '2', 'name' => 'شمال سيناء'],
            ['id' => '49', 'countries_id' => '2', 'name' => 'جنوب سيناء'],
            ['id' => '50', 'countries_id' => '3', 'name' => 'الرياض'],
            ['id' => '51', 'countries_id' => '3', 'name' => 'جدة'],
            ['id' => '52', 'countries_id' => '3', 'name' => 'مكة المكرمة'],
            ['id' => '53', 'countries_id' => '3', 'name' => 'المدينة المنورة'],
            ['id' => '54', 'countries_id' => '3', 'name' => 'الدمام'],
            ['id' => '55', 'countries_id' => '3', 'name' => 'الأحساء'],
            ['id' => '56', 'countries_id' => '3', 'name' => 'القطيف'],
            ['id' => '57', 'countries_id' => '3', 'name' => 'تبوك'],
            ['id' => '58', 'countries_id' => '3', 'name' => 'الطائف'],
            ['id' => '59', 'countries_id' => '3', 'name' => 'الجبيل'],
            ['id' => '60', 'countries_id' => '3', 'name' => 'الخبر'],
            ['id' => '61', 'countries_id' => '3', 'name' => 'حائل'],
            ['id' => '62', 'countries_id' => '3', 'name' => 'نجران'],
            ['id' => '63', 'countries_id' => '3', 'name' => 'جازان'],
            ['id' => '64', 'countries_id' => '3', 'name' => 'عرعر'],
            ['id' => '65', 'countries_id' => '3', 'name' => 'الحوية'],
            ['id' => '66', 'countries_id' => '3', 'name' => 'ينبع'],
            ['id' => '67', 'countries_id' => '3', 'name' => 'الباحة'],
            ['id' => '68', 'countries_id' => '3', 'name' => 'الخرج'],
            ['id' => '69', 'countries_id' => '3', 'name' => 'حفر الباطن'],
            ['id' => '70', 'countries_id' => '3', 'name' => 'الظهران'],
            ['id' => '71', 'countries_id' => '3', 'name' => 'الشرقية'],
            ['id' => '72', 'countries_id' => '3', 'name' => 'الوادي الجديد'],
            ['id' => '73', 'countries_id' => '3', 'name' => 'عنيزة'],
            ['id' => '74', 'countries_id' => '3', 'name' => 'القصيم'],
            ['id' => '75', 'countries_id' => '3', 'name' => 'النماص'],
            ['id' => '76', 'countries_id' => '3', 'name' => 'جيزان'],
            ['id' => '77', 'countries_id' => '3', 'name' => 'أبها'],
            ['id' => '78', 'countries_id' => '4', 'name' => 'أبوظبي'],
            ['id' => '79', 'countries_id' => '4', 'name' => 'دبي'],
            ['id' => '80', 'countries_id' => '4', 'name' => 'الشارقة'],
            ['id' => '81', 'countries_id' => '4', 'name' => 'عجمان'],
            ['id' => '82', 'countries_id' => '4', 'name' => 'أم القيوين'],
            ['id' => '83', 'countries_id' => '4', 'name' => 'رأس الخيمة'],
            ['id' => '84', 'countries_id' => '4', 'name' => 'الفجيرة'],
            ['id' => '85', 'countries_id' => '4', 'name' => 'خورفكان'],
            ['id' => '86', 'countries_id' => '4', 'name' => 'العين'],
            ['id' => '87', 'countries_id' => '5', 'name' => 'بغداد'],
            ['id' => '88', 'countries_id' => '5', 'name' => 'البصرة'],
            ['id' => '89', 'countries_id' => '5', 'name' => 'الموصل'],
            ['id' => '90', 'countries_id' => '5', 'name' => 'كركوك'],
            ['id' => '91', 'countries_id' => '5', 'name' => 'النجف'],
            ['id' => '92', 'countries_id' => '5', 'name' => 'بابل'],
            ['id' => '93', 'countries_id' => '5', 'name' => 'السليمانية'],
            ['id' => '94', 'countries_id' => '5', 'name' => 'أربيل'],
            ['id' => '95', 'countries_id' => '5', 'name' => 'دهوك'],
            ['id' => '96', 'countries_id' => '5', 'name' => 'صلاح الدين'],
            ['id' => '97', 'countries_id' => '5', 'name' => 'واسط'],
            ['id' => '98', 'countries_id' => '5', 'name' => 'الأنبار'],
            ['id' => '99', 'countries_id' => '5', 'name' => 'ديالى'],
            ['id' => '100', 'countries_id' => '5', 'name' => 'ذي قار'],
            ['id' => '101', 'countries_id' => '5', 'name' => 'ميسان'],
            ['id' => '102', 'countries_id' => '5', 'name' => 'نينوى'],
            ['id' => '103', 'countries_id' => '5', 'name' => 'الديوانية'],
            ['id' => '104', 'countries_id' => '5', 'name' => 'كربلاء'],
            ['id' => '105', 'countries_id' => '5', 'name' => 'المثنى'],
            ['id' => '106', 'countries_id' => '5', 'name' => 'القادسية'],
            ['id' => '107', 'countries_id' => '5', 'name' => 'ميسان'],
            ['id' => '108', 'countries_id' => '6', 'name' => 'عمان'],
            ['id' => '109', 'countries_id' => '6', 'name' => 'الزرقاء'],
            ['id' => '110', 'countries_id' => '6', 'name' => 'إربد'],
            ['id' => '111', 'countries_id' => '6', 'name' => 'العقبة'],
            ['id' => '112', 'countries_id' => '6', 'name' => 'الكرك'],
            ['id' => '113', 'countries_id' => '6', 'name' => 'معان'],
            ['id' => '114', 'countries_id' => '6', 'name' => 'الطفيلة'],
            ['id' => '115', 'countries_id' => '6', 'name' => 'جرش'],
            ['id' => '116', 'countries_id' => '6', 'name' => 'عجلون'],
            ['id' => '117', 'countries_id' => '6', 'name' => 'المفرق'],
            ['id' => '118', 'countries_id' => '6', 'name' => 'السلط'],
            ['id' => '119', 'countries_id' => '6', 'name' => 'مادبا'],
            ['id' => '120', 'countries_id' => '7', 'name' => 'المنامة'],
            ['id' => '121', 'countries_id' => '7', 'name' => 'الرفاع'],
            ['id' => '122', 'countries_id' => '7', 'name' => 'المحرق'],
            ['id' => '123', 'countries_id' => '7', 'name' => 'عالي'],
            ['id' => '124', 'countries_id' => '7', 'name' => 'الحد'],
            ['id' => '125', 'countries_id' => '7', 'name' => 'مدينة عيسى'],
            ['id' => '126', 'countries_id' => '7', 'name' => 'مدينة حمد'],
            ['id' => '127', 'countries_id' => '7', 'name' => 'النويدرات'],
            ['id' => '128', 'countries_id' => '7', 'name' => 'الدير'],
            ['id' => '129', 'countries_id' => '8', 'name' => 'صنعاء'],
            ['id' => '130', 'countries_id' => '8', 'name' => 'عدن'],
            ['id' => '131', 'countries_id' => '8', 'name' => 'تعز'],
            ['id' => '132', 'countries_id' => '8', 'name' => 'الحديدة'],
            ['id' => '133', 'countries_id' => '8', 'name' => 'إب'],
            ['id' => '134', 'countries_id' => '8', 'name' => 'المكلا'],
            ['id' => '135', 'countries_id' => '8', 'name' => 'ذمار'],
            ['id' => '136', 'countries_id' => '8', 'name' => 'عمران'],
            ['id' => '137', 'countries_id' => '8', 'name' => 'البيضاء'],
            ['id' => '138', 'countries_id' => '8', 'name' => 'رداع'],
            ['id' => '139', 'countries_id' => '9', 'name' => 'الدوحة'],
            ['id' => '140', 'countries_id' => '9', 'name' => 'الريان'],
            ['id' => '141', 'countries_id' => '9', 'name' => 'الوكرة'],
            ['id' => '142', 'countries_id' => '9', 'name' => 'الخور'],
            ['id' => '143', 'countries_id' => '9', 'name' => 'الشحانية'],
            ['id' => '144', 'countries_id' => '9', 'name' => 'الزبارة'],
            ['id' => '145', 'countries_id' => '9', 'name' => 'السيلية'],
            ['id' => '146', 'countries_id' => '9', 'name' => 'الخيسة'],
            ['id' => '147', 'countries_id' => '9', 'name' => 'الجميلية'],
            ['id' => '148', 'countries_id' => '9', 'name' => 'الوكير'],
            ['id' => '151', 'countries_id' => '10', 'name' => 'ولاية أدرار'],
            ['id' => '152', 'countries_id' => '10', 'name' => 'ولاية الشلف'],
            ['id' => '153', 'countries_id' => '10', 'name' => 'ولاية الأغواط'],
            ['id' => '154', 'countries_id' => '10', 'name' => 'ولاية أم البواقي'],
            ['id' => '155', 'countries_id' => '10', 'name' => 'ولاية باتنة'],
            ['id' => '156', 'countries_id' => '10', 'name' => 'ولاية بجاية'],
            ['id' => '157', 'countries_id' => '10', 'name' => 'ولاية بسكرة'],
            ['id' => '158', 'countries_id' => '10', 'name' => 'ولاية بشار'],
            ['id' => '159', 'countries_id' => '10', 'name' => 'ولاية البليدة'],
            ['id' => '160', 'countries_id' => '10', 'name' => 'ولاية البويرة'],
            ['id' => '161', 'countries_id' => '10', 'name' => 'ولاية تمنراست'],
            ['id' => '162', 'countries_id' => '10', 'name' => 'ولاية تبسة'],
            ['id' => '163', 'countries_id' => '10', 'name' => 'ولاية تلمسان'],
            ['id' => '164', 'countries_id' => '10', 'name' => 'ولاية تيارت'],
            ['id' => '165', 'countries_id' => '10', 'name' => 'ولاية تيزي وزو'],
            ['id' => '166', 'countries_id' => '10', 'name' => 'ولاية الجزائر'],
            ['id' => '167', 'countries_id' => '10', 'name' => 'ولاية الجلفة'],
            ['id' => '168', 'countries_id' => '10', 'name' => 'ولاية جيجل'],
            ['id' => '169', 'countries_id' => '10', 'name' => 'ولاية سطيف'],
            ['id' => '170', 'countries_id' => '10', 'name' => 'ولاية سعيدة'],
            ['id' => '171', 'countries_id' => '10', 'name' => 'ولاية سكيكدة'],
            ['id' => '172', 'countries_id' => '10', 'name' => 'ولاية سيدي بلعباس'],
            ['id' => '173', 'countries_id' => '10', 'name' => 'ولاية عنابة'],
            ['id' => '174', 'countries_id' => '10', 'name' => 'ولاية قالمة'],
            ['id' => '175', 'countries_id' => '10', 'name' => 'ولاية قسنطينة'],
            ['id' => '176', 'countries_id' => '10', 'name' => 'ولاية المدية'],
            ['id' => '177', 'countries_id' => '10', 'name' => 'ولاية مستغانم'],
            ['id' => '178', 'countries_id' => '10', 'name' => 'ولاية المسيلة'],
            ['id' => '179', 'countries_id' => '10', 'name' => 'ولاية معسكر'],
            ['id' => '180', 'countries_id' => '10', 'name' => 'ولاية ورقلة'],
            ['id' => '181', 'countries_id' => '10', 'name' => 'ولاية وهران'],
            ['id' => '182', 'countries_id' => '10', 'name' => 'ولاية البيض'],
            ['id' => '183', 'countries_id' => '10', 'name' => 'ولاية إليزي'],
            ['id' => '184', 'countries_id' => '10', 'name' => 'ولاية برج بوعريريج'],
            ['id' => '185', 'countries_id' => '10', 'name' => 'ولاية بومرداس'],
            ['id' => '186', 'countries_id' => '10', 'name' => 'ولاية الطارف'],
            ['id' => '187', 'countries_id' => '10', 'name' => 'ولاية تندوف'],
            ['id' => '188', 'countries_id' => '10', 'name' => 'ولاية تيسمسيلت'],
            ['id' => '189', 'countries_id' => '10', 'name' => 'ولاية الوادي'],
            ['id' => '190', 'countries_id' => '10', 'name' => 'ولاية خنشلة'],
            ['id' => '191', 'countries_id' => '10', 'name' => 'ولاية سوق أهراس'],
            ['id' => '192', 'countries_id' => '10', 'name' => 'ولاية تيبازة'],
            ['id' => '193', 'countries_id' => '10', 'name' => 'ولاية ميلة'],
            ['id' => '194', 'countries_id' => '10', 'name' => 'ولاية عين الدفلى'],
            ['id' => '195', 'countries_id' => '10', 'name' => 'ولاية النعامة'],
            ['id' => '196', 'countries_id' => '10', 'name' => 'ولاية عين تموشنت'],
            ['id' => '197', 'countries_id' => '10', 'name' => 'ولاية غرداية'],
            ['id' => '198', 'countries_id' => '10', 'name' => 'ولاية غليزان'],
            ['id' => '199', 'countries_id' => '10', 'name' => 'ولاية تيميمون'],
            ['id' => '200', 'countries_id' => '10', 'name' => 'ولاية برج باجي مختار'],
            ['id' => '201', 'countries_id' => '10', 'name' => 'ولاية أولاد جلال'],
            ['id' => '202', 'countries_id' => '10', 'name' => 'ولاية بني عباس'],
            ['id' => '203', 'countries_id' => '10', 'name' => 'ولاية إن صالح'],
            ['id' => '204', 'countries_id' => '10', 'name' => 'ولاية إن قزام'],
            ['id' => '205', 'countries_id' => '10', 'name' => 'ولاية تقرت'],
            ['id' => '206', 'countries_id' => '10', 'name' => 'ولاية جانت'],
            ['id' => '207', 'countries_id' => '10', 'name' => 'ولاية المغير'],
            ['id' => '208', 'countries_id' => '10', 'name' => 'ولاية المنيعة'],
            ['id' => '209', 'countries_id' => '11', 'name' => 'الدار البيضاء'],
            ['id' => '210', 'countries_id' => '11', 'name' => 'الرباط'],
            ['id' => '211', 'countries_id' => '11', 'name' => 'فاس'],
            ['id' => '212', 'countries_id' => '11', 'name' => 'مراكش'],
            ['id' => '213', 'countries_id' => '11', 'name' => 'طنجة'],
            ['id' => '214', 'countries_id' => '11', 'name' => 'أكادير'],
            ['id' => '215', 'countries_id' => '11', 'name' => 'مكناس'],
            ['id' => '216', 'countries_id' => '11', 'name' => 'وجدة'],
            ['id' => '217', 'countries_id' => '11', 'name' => 'القنيطرة'],
            ['id' => '218', 'countries_id' => '11', 'name' => 'تطوان'],
            ['id' => '219', 'countries_id' => '11', 'name' => 'أسفي'],
            ['id' => '220', 'countries_id' => '11', 'name' => 'الصويرة'],
            ['id' => '221', 'countries_id' => '12', 'name' => 'تونس'],
            ['id' => '222', 'countries_id' => '12', 'name' => 'صفاقس'],
            ['id' => '223', 'countries_id' => '12', 'name' => 'سوسة'],
            ['id' => '224', 'countries_id' => '12', 'name' => 'قفصة'],
            ['id' => '225', 'countries_id' => '12', 'name' => 'قابس'],
            ['id' => '226', 'countries_id' => '12', 'name' => 'القصرين'],
            ['id' => '227', 'countries_id' => '12', 'name' => 'مدنين'],
            ['id' => '228', 'countries_id' => '12', 'name' => 'سيدي بوزيد'],
            ['id' => '229', 'countries_id' => '12', 'name' => 'المهدية'],
            ['id' => '230', 'countries_id' => '12', 'name' => 'الكاف'],
            ['id' => '231', 'countries_id' => '12', 'name' => 'منوبة'],
            ['id' => '232', 'countries_id' => '12', 'name' => 'باجة'],
            ['id' => '233', 'countries_id' => '12', 'name' => 'بن عروس'],
            ['id' => '234', 'countries_id' => '12', 'name' => 'تطاوين'],
            ['id' => '235', 'countries_id' => '12', 'name' => 'نابل'],
            ['id' => '236', 'countries_id' => '12', 'name' => 'زغوان'],
            ['id' => '237', 'countries_id' => '12', 'name' => 'سليانة'],
            ['id' => '238', 'countries_id' => '12', 'name' => 'القيروان'],
            ['id' => '239', 'countries_id' => '12', 'name' => 'المنستير'],
            ['id' => '240', 'countries_id' => '12', 'name' => 'جندوبة'],
            ['id' => '241', 'countries_id' => '12', 'name' => 'الكرم'],
            ['id' => '242', 'countries_id' => '12', 'name' => 'توزر'],
            ['id' => '243', 'countries_id' => '12', 'name' => 'القصر الجديد'],
            ['id' => '244', 'countries_id' => '12', 'name' => 'قابس'],
            ['id' => '245', 'countries_id' => '12', 'name' => 'بنزرت'],
            ['id' => '246', 'countries_id' => '13', 'name' => 'طرابلس'],
            ['id' => '247', 'countries_id' => '13', 'name' => 'بنغازي'],
            ['id' => '248', 'countries_id' => '13', 'name' => 'مصراتة'],
            ['id' => '249', 'countries_id' => '13', 'name' => 'تاجوراء'],
            ['id' => '250', 'countries_id' => '13', 'name' => 'الزاوية'],
            ['id' => '251', 'countries_id' => '13', 'name' => 'مصراته'],
            ['id' => '252', 'countries_id' => '13', 'name' => 'درنة'],
            ['id' => '253', 'countries_id' => '13', 'name' => 'البيضاء'],
            ['id' => '254', 'countries_id' => '13', 'name' => 'زليتن'],
            ['id' => '255', 'countries_id' => '13', 'name' => 'الخمس'],
            ['id' => '256', 'countries_id' => '13', 'name' => 'سبها'],
            ['id' => '257', 'countries_id' => '13', 'name' => 'غات'],
            ['id' => '258', 'countries_id' => '13', 'name' => 'المرج'],
            ['id' => '259', 'countries_id' => '13', 'name' => 'زوارة'],
            ['id' => '260', 'countries_id' => '14', 'name' => 'دمشق'],
            ['id' => '261', 'countries_id' => '14', 'name' => 'حلب'],
            ['id' => '262', 'countries_id' => '14', 'name' => 'حمص'],
            ['id' => '263', 'countries_id' => '14', 'name' => 'حماة'],
            ['id' => '264', 'countries_id' => '14', 'name' => 'دير الزور'],
            ['id' => '265', 'countries_id' => '14', 'name' => 'الرقة'],
            ['id' => '266', 'countries_id' => '14', 'name' => 'اللاذقية'],
            ['id' => '267', 'countries_id' => '14', 'name' => 'طرطوس'],
            ['id' => '268', 'countries_id' => '14', 'name' => 'الحسكة'],
            ['id' => '269', 'countries_id' => '14', 'name' => 'إدلب'],
            ['id' => '270', 'countries_id' => '14', 'name' => 'درعا'],
            ['id' => '271', 'countries_id' => '14', 'name' => 'السويداء'],
            ['id' => '272', 'countries_id' => '14', 'name' => 'القامشلي'],
            ['id' => '273', 'countries_id' => '14', 'name' => 'الحرس'],
            ['id' => '342', 'countries_id' => '15', 'name' => 'الخرطوم'],
            ['id' => '274', 'countries_id' => '15', 'name' => 'أم درمان'],
            ['id' => '275', 'countries_id' => '15', 'name' => 'الأبيض'],
            ['id' => '276', 'countries_id' => '15', 'name' => 'بورتسودان'],
            ['id' => '277', 'countries_id' => '15', 'name' => 'النهود'],
            ['id' => '278', 'countries_id' => '15', 'name' => 'الجزيرة'],
            ['id' => '279', 'countries_id' => '15', 'name' => 'كسلا'],
            ['id' => '280', 'countries_id' => '15', 'name' => 'القضارف'],
            ['id' => '281', 'countries_id' => '15', 'name' => 'عطبرة'],
            ['id' => '282', 'countries_id' => '15', 'name' => 'الدمازين'],
            ['id' => '283', 'countries_id' => '15', 'name' => 'أبو حمد'],
            ['id' => '284', 'countries_id' => '15', 'name' => 'كوستي'],
            ['id' => '285', 'countries_id' => '15', 'name' => 'شندي'],
            ['id' => '286', 'countries_id' => '15', 'name' => 'مدني'],
            ['id' => '287', 'countries_id' => '15', 'name' => 'الفاشر'],
            ['id' => '288', 'countries_id' => '15', 'name' => 'أبو زعبل'],
            ['id' => '289', 'countries_id' => '15', 'name' => 'سوك اللوك'],
            ['id' => '290', 'countries_id' => '15', 'name' => 'القيت'],
            ['id' => '291', 'countries_id' => '16', 'name' => 'الكويت'],
            ['id' => '292', 'countries_id' => '16', 'name' => 'الأحمدي'],
            ['id' => '293', 'countries_id' => '16', 'name' => 'حولي'],
            ['id' => '294', 'countries_id' => '16', 'name' => 'الفروانية'],
            ['id' => '295', 'countries_id' => '16', 'name' => 'الجهراء'],
            ['id' => '296', 'countries_id' => '16', 'name' => 'مبارك الكبير'],
            ['id' => '297', 'countries_id' => '17', 'name' => 'بيروت'],
            ['id' => '298', 'countries_id' => '17', 'name' => 'طرابلس'],
            ['id' => '299', 'countries_id' => '17', 'name' => 'صيدا'],
            ['id' => '300', 'countries_id' => '17', 'name' => 'زحلة'],
            ['id' => '301', 'countries_id' => '17', 'name' => 'بعلبك'],
            ['id' => '302', 'countries_id' => '17', 'name' => 'جبيل'],
            ['id' => '303', 'countries_id' => '17', 'name' => 'صور'],
            ['id' => '304', 'countries_id' => '17', 'name' => 'النبطية'],
            ['id' => '305', 'countries_id' => '18', 'name' => 'مسقط'],
            ['id' => '306', 'countries_id' => '18', 'name' => 'صلالة'],
            ['id' => '307', 'countries_id' => '18', 'name' => 'صحار'],
            ['id' => '308', 'countries_id' => '18', 'name' => 'السيب'],
            ['id' => '309', 'countries_id' => '18', 'name' => 'صحم'],
            ['id' => '310', 'countries_id' => '18', 'name' => 'نزوى'],
            ['id' => '311', 'countries_id' => '18', 'name' => 'البريمي'],
            ['id' => '312', 'countries_id' => '18', 'name' => 'صور'],
            ['id' => '313', 'countries_id' => '19', 'name' => 'نواكشوط'],
            ['id' => '314', 'countries_id' => '19', 'name' => 'نواذيبو'],
            ['id' => '315', 'countries_id' => '19', 'name' => 'كيفة'],
            ['id' => '316', 'countries_id' => '19', 'name' => 'روصو'],
            ['id' => '317', 'countries_id' => '19', 'name' => 'أطار'],
            ['id' => '318', 'countries_id' => '19', 'name' => 'آكفونيت'],
            ['id' => '319', 'countries_id' => '19', 'name' => 'أطار'],
            ['id' => '320', 'countries_id' => '19', 'name' => 'بير أم أكرين'],
            ['id' => '321', 'countries_id' => '19', 'name' => 'كيهيدي'],
            ['id' => '322', 'countries_id' => '19', 'name' => 'سيلبابي'],
            ['id' => '323', 'countries_id' => '19', 'name' => 'روصو'],
            ['id' => '324', 'countries_id' => '19', 'name' => 'باسكنو'],
            ['id' => '343', 'countries_id' => '20', 'name' => 'مقديشو'],
            ['id' => '325', 'countries_id' => '20', 'name' => 'هرجيسا'],
            ['id' => '326', 'countries_id' => '20', 'name' => 'بوساسو'],
            ['id' => '327', 'countries_id' => '20', 'name' => 'بيرة'],
            ['id' => '328', 'countries_id' => '20', 'name' => 'كسمايو'],
            ['id' => '329', 'countries_id' => '20', 'name' => 'ماركا'],
            ['id' => '330', 'countries_id' => '20', 'name' => 'جوهرة'],
            ['id' => '331', 'countries_id' => '20', 'name' => 'جالكعيو'],
            ['id' => '332', 'countries_id' => '20', 'name' => 'دينل'],
            ['id' => '333', 'countries_id' => '20', 'name' => 'أفجوي'],
            ['id' => '334', 'countries_id' => '20', 'name' => 'كيسمايو'],
            ['id' => '335', 'countries_id' => '20', 'name' => 'بونتلاند'],
            ['id' => '336', 'countries_id' => '20', 'name' => 'جاروا'],
            ['id' => '337', 'countries_id' => '20', 'name' => 'بيراوا'],
            ['id' => '338', 'countries_id' => '20', 'name' => 'بايدوا'],
            ['id' => '339', 'countries_id' => '20', 'name' => 'بوراما'],
            ['id' => '340', 'countries_id' => '20', 'name' => 'بالادواين'],
            ['id' => '341', 'countries_id' => '20', 'name' => 'جابيلي'],
        ];
        foreach ($cities as $city) {
            $subCategoryData = cities::create([
                'id' => $city['id'],
                'name' => $city['name'],
                'country_id' => $city['countries_id'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
            $subCategoryData->save();
        }
    }
}
