<?php

namespace Database\Seeders;

use App\Models\cities;
use App\Models\city;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            ['id' => '1', 'countries_id' => '1', 'name' => json_encode(['ar' => 'خان يونس', 'en' => 'Khan Younis'])],
            ['id' => '2', 'countries_id' => '1', 'name' => json_encode(['ar' => 'رفح', 'en' => 'Rafah'])],
            ['id' => '3', 'countries_id' => '1', 'name' => json_encode(['ar' => 'غزة', 'en' => 'Gaza City'])],
            ['id' => '4', 'countries_id' => '1', 'name' => json_encode(['ar' => 'دير البلح', 'en' => 'Deir al-Balah'])],
            ['id' => '5', 'countries_id' => '1', 'name' => json_encode(['ar' => 'بيت حانون', 'en' => 'Beit Hanoun'])],
            ['id' => '6', 'countries_id' => '1', 'name' => json_encode(['ar' => 'بيت لاهيا', 'en' => 'Beit Lahia'])],
            ['id' => '7', 'countries_id' => '1', 'name' => json_encode(['ar' => 'جباليا', 'en' => 'Jabalia'])],
            ['id' => '8', 'countries_id' => '1', 'name' => json_encode(['ar' => 'النصيرات', 'en' => 'Nuseirat'])],
            ['id' => '9', 'countries_id' => '1', 'name' => json_encode(['ar' => 'البريج', 'en' => 'Al-Bureij'])],
            ['id' => '10', 'countries_id' => '1', 'name' => json_encode(['ar' => 'المغازي', 'en' => 'Al-Maghazi'])],
            ['id' => '11', 'countries_id' => '1', 'name' => json_encode(['ar' => 'الزوايدة', 'en' => 'Al-Zawayda'])],

            ['id' => '12', 'countries_id' => '1', 'name' => json_encode(['ar' => 'رام الله', 'en' => 'Ramallah'])],
            ['id' => '13', 'countries_id' => '1', 'name' => json_encode(['ar' => 'الخليل', 'en' => 'Alkalil'])],
            ['id' => '14', 'countries_id' => '1', 'name' => json_encode(['ar' => 'بيت لحم', 'en' => 'Bethlehem'])],
            ['id' => '15', 'countries_id' => '1', 'name' => json_encode(['ar' => 'نابلس', 'en' => 'Nablus'])],
            ['id' => '16', 'countries_id' => '1', 'name' => json_encode(['ar' => 'جنين', 'en' => 'Jenin'])],
            ['id' => '17', 'countries_id' => '1', 'name' => json_encode(['ar' => 'سلفيت', 'en' => 'Salfit'])],
            ['id' => '18', 'countries_id' => '1', 'name' => json_encode(['ar' => 'عسقلان', 'en' => 'Askalan'])],
            ['id' => '19', 'countries_id' => '1', 'name' => json_encode(['ar' => 'بئر السبع', 'en' => 'Beersabaa'])],
            ['id' => '20', 'countries_id' => '1', 'name' => json_encode(['ar' => 'طبريا', 'en' => 'Tiberias'])],
            ['id' => '21', 'countries_id' => '1', 'name' => json_encode(['ar' => 'الناصرة', 'en' => 'Nasiraa'])],
            ['id' => '22', 'countries_id' => '1', 'name' => json_encode(['ar' => 'بيسان', 'en' => 'Bessan'])],
            ['id' => '23', 'countries_id' => '1', 'name' => json_encode(['ar' => 'اللد', 'en' => 'Lod'])],
            ['id' => '24', 'countries_id' => '1', 'name' => json_encode(['ar' => 'الرملة', 'en' => 'Ramla'])],
            ['id' => '25', 'countries_id' => '1', 'name' => json_encode(['ar' => 'طولكرم', 'en' => 'Tulkarm'])],
            ['id' => '26', 'countries_id' => '1', 'name' => json_encode(['ar' => 'قلقيلية', 'en' => 'Qalqilya'])],
            ['id' => '27', 'countries_id' => '1', 'name' => json_encode(['ar' => 'عكا', 'en' => 'Akka'])],
            ['id' => '28', 'countries_id' => '1', 'name' => json_encode(['ar' => 'حيفا', 'en' => 'Haifa'])],
            ['id' => '29', 'countries_id' => '1', 'name' => json_encode(['ar' => 'يافا', 'en' => 'Yaffa'])],
            ['id' => '30', 'countries_id' => '1', 'name' => json_encode(['ar' => 'صفد', 'en' => 'Safed'])],
            ['id' => '31', 'countries_id' => '1', 'name' => json_encode(['ar' => 'أريحا', 'en' => 'Arihaa'])],

            // Egypt Cities
            ['id' => '32', 'countries_id' => '2', 'name' => json_encode(['ar' => 'القاهرة', 'en' => 'Cairo'])],
            ['id' => '33', 'countries_id' => '2', 'name' => json_encode(['ar' => 'الإسكندرية', 'en' => 'Alexandria'])],
            ['id' => '34', 'countries_id' => '2', 'name' => json_encode(['ar' => 'الجيزة', 'en' => 'Giza'])],
            ['id' => '35', 'countries_id' => '2', 'name' => json_encode(['ar' => 'بورسعيد', 'en' => 'Port Said'])],
            ['id' => '36', 'countries_id' => '2', 'name' => json_encode(['ar' => 'السويس', 'en' => 'Suez'])],
            ['id' => '37', 'countries_id' => '2', 'name' => json_encode(['ar' => 'الأقصر', 'en' => 'Luxor'])],
            ['id' => '38', 'countries_id' => '2', 'name' => json_encode(['ar' => 'أسوان', 'en' => 'Aswan'])],
            ['id' => '39', 'countries_id' => '2', 'name' => json_encode(['ar' => 'أسيوط', 'en' => 'Asyut'])],
            ['id' => '40', 'countries_id' => '2', 'name' => json_encode(['ar' => 'المنصورة', 'en' => 'Mansoura'])],
            ['id' => '41', 'countries_id' => '2', 'name' => json_encode(['ar' => 'الغردقة', 'en' => 'Hurghada'])],
            ['id' => '42', 'countries_id' => '2', 'name' => json_encode(['ar' => 'شرم الشيخ', 'en' => 'Sharm El Sheikh'])],
            ['id' => '43', 'countries_id' => '2', 'name' => json_encode(['ar' => 'الفيوم', 'en' => 'Faiyum'])],
            ['id' => '44', 'countries_id' => '2', 'name' => json_encode(['ar' => 'دمياط', 'en' => 'Damietta'])],
            ['id' => '45', 'countries_id' => '2', 'name' => json_encode(['ar' => 'سوهاج', 'en' => 'Sohag'])],
            ['id' => '46', 'countries_id' => '2', 'name' => json_encode(['ar' => 'قنا', 'en' => 'Qena'])],
            ['id' => '47', 'countries_id' => '2', 'name' => json_encode(['ar' => 'طنطا', 'en' => 'Tanta'])],
            ['id' => '48', 'countries_id' => '2', 'name' => json_encode(['ar' => 'الزقازيق', 'en' => 'Zagazig'])],
            ['id' => '49', 'countries_id' => '2', 'name' => json_encode(['ar' => 'بني سويف', 'en' => 'Beni Suef'])],
            ['id' => '50', 'countries_id' => '2', 'name' => json_encode(['ar' => 'كفر الشيخ', 'en' => 'Kafr El Sheikh'])],
            ['id' => '51', 'countries_id' => '2', 'name' => json_encode(['ar' => 'مرسى مطروح', 'en' => 'Marsa Matruh'])],
            ['id' => '52', 'countries_id' => '2', 'name' => json_encode(['ar' => 'الإسماعيلية', 'en' => 'Ismailia'])],
            ['id' => '53', 'countries_id' => '2', 'name' => json_encode(['ar' => 'العريش', 'en' => 'Arish'])],
            ['id' => '54', 'countries_id' => '2', 'name' => json_encode(['ar' => 'المنيا', 'en' => 'Minya'])],
            ['id' => '55', 'countries_id' => '2', 'name' => json_encode(['ar' => 'المحلة الكبرى', 'en' => 'El Mahalla El Kubra'])],
            ['id' => '101', 'countries_id' => '3', 'name' => json_encode(['ar' => 'الرياض', 'en' => 'Riyadh'])],
            ['id' => '102', 'countries_id' => '3', 'name' => json_encode(['ar' => 'جدة', 'en' => 'Jeddah'])],
            ['id' => '103', 'countries_id' => '3', 'name' => json_encode(['ar' => 'مكة المكرمة', 'en' => 'Mecca'])],
            ['id' => '104', 'countries_id' => '3', 'name' => json_encode(['ar' => 'المدينة المنورة', 'en' => 'Medina'])],
            ['id' => '105', 'countries_id' => '3', 'name' => json_encode(['ar' => 'الدمام', 'en' => 'Dammam'])],
            ['id' => '106', 'countries_id' => '3', 'name' => json_encode(['ar' => 'الخبر', 'en' => 'Khobar'])],
            ['id' => '107', 'countries_id' => '3', 'name' => json_encode(['ar' => 'الطائف', 'en' => 'Taif'])],
            ['id' => '108', 'countries_id' => '3', 'name' => json_encode(['ar' => 'بريدة', 'en' => 'Buraidah'])],
            ['id' => '109', 'countries_id' => '3', 'name' => json_encode(['ar' => 'حائل', 'en' => 'Hail'])],
            ['id' => '110', 'countries_id' => '3', 'name' => json_encode(['ar' => 'أبها', 'en' => 'Abha'])],
            ['id' => '111', 'countries_id' => '3', 'name' => json_encode(['ar' => 'جازان', 'en' => 'Jazan'])],
            ['id' => '112', 'countries_id' => '3', 'name' => json_encode(['ar' => 'نجران', 'en' => 'Najran'])],
            ['id' => '113', 'countries_id' => '3', 'name' => json_encode(['ar' => 'سكاكا', 'en' => 'Sakaka'])],
            ['id' => '114', 'countries_id' => '3', 'name' => json_encode(['ar' => 'ينبع', 'en' => 'Yanbu'])],
            ['id' => '115', 'countries_id' => '3', 'name' => json_encode(['ar' => 'الجبيل', 'en' => 'Jubail'])],
            ['id' => '116', 'countries_id' => '3', 'name' => json_encode(['ar' => 'تبوك', 'en' => 'Tabuk'])],
            ['id' => '117', 'countries_id' => '3', 'name' => json_encode(['ar' => 'الخرج', 'en' => 'Al Kharj'])],
            ['id' => '118', 'countries_id' => '3', 'name' => json_encode(['ar' => 'عنيزة', 'en' => 'Unaizah'])],
            ['id' => '119', 'countries_id' => '3', 'name' => json_encode(['ar' => 'القطيف', 'en' => 'Qatif'])],


            ['id' => '201', 'countries_id' => '4', 'name' => json_encode(['ar' => 'دبي', 'en' => 'Dubai'])],
            ['id' => '202', 'countries_id' => '4', 'name' => json_encode(['ar' => 'أبوظبي', 'en' => 'Abu Dhabi'])],
            ['id' => '203', 'countries_id' => '4', 'name' => json_encode(['ar' => 'الشارقة', 'en' => 'Sharjah'])],
            ['id' => '204', 'countries_id' => '4', 'name' => json_encode(['ar' => 'عجمان', 'en' => 'Ajman'])],
            ['id' => '205', 'countries_id' => '4', 'name' => json_encode(['ar' => 'رأس الخيمة', 'en' => 'Ras Al Khaimah'])],
            ['id' => '206', 'countries_id' => '4', 'name' => json_encode(['ar' => 'الفجيرة', 'en' => 'Fujairah'])],
            ['id' => '207', 'countries_id' => '4', 'name' => json_encode(['ar' => 'أم القيوين', 'en' => 'Umm Al Quwain'])],
            ['id' => '208', 'countries_id' => '4', 'name' => json_encode(['ar' => 'خورفكان', 'en' => 'Khor Fakkan'])],


            ['id' => '301', 'countries_id' => '5', 'name' => json_encode(['ar' => 'بغداد', 'en' => 'Baghdad'])],
            ['id' => '302', 'countries_id' => '5', 'name' => json_encode(['ar' => 'البصرة', 'en' => 'Basra'])],
            ['id' => '303', 'countries_id' => '5', 'name' => json_encode(['ar' => 'الموصل', 'en' => 'Mosul'])],
            ['id' => '304', 'countries_id' => '5', 'name' => json_encode(['ar' => 'أربيل', 'en' => 'Erbil'])],
            ['id' => '305', 'countries_id' => '5', 'name' => json_encode(['ar' => 'النجف', 'en' => 'Najaf'])],
            ['id' => '306', 'countries_id' => '5', 'name' => json_encode(['ar' => 'كربلاء', 'en' => 'Karbala'])],
            ['id' => '307', 'countries_id' => '5', 'name' => json_encode(['ar' => 'السليمانية', 'en' => 'Sulaymaniyah'])],
            ['id' => '308', 'countries_id' => '5', 'name' => json_encode(['ar' => 'كركوك', 'en' => 'Kirkuk'])],
            ['id' => '309', 'countries_id' => '5', 'name' => json_encode(['ar' => 'الأنبار', 'en' => 'Anbar'])],
            ['id' => '310', 'countries_id' => '5', 'name' => json_encode(['ar' => 'الديوانية', 'en' => 'Diwaniyah'])],
            ['id' => '311', 'countries_id' => '5', 'name' => json_encode(['ar' => 'ميسان', 'en' => 'Maysan'])],
            ['id' => '312', 'countries_id' => '5', 'name' => json_encode(['ar' => 'ذي قار', 'en' => 'Dhi Qar'])],
            ['id' => '313', 'countries_id' => '5', 'name' => json_encode(['ar' => 'بابل', 'en' => 'Babel'])],
            ['id' => '314', 'countries_id' => '5', 'name' => json_encode(['ar' => 'ديالى', 'en' => 'Diyala'])],
            ['id' => '315', 'countries_id' => '5', 'name' => json_encode(['ar' => 'صلاح الدين', 'en' => 'Salah al-Din'])],
            ['id' => '316', 'countries_id' => '5', 'name' => json_encode(['ar' => 'نينوى', 'en' => 'Nineveh'])],
            ['id' => '317', 'countries_id' => '5', 'name' => json_encode(['ar' => 'واسط', 'en' => 'Wasit'])],
            ['id' => '318', 'countries_id' => '5', 'name' => json_encode(['ar' => 'المثنى', 'en' => 'Muthanna'])],
            ['id' => '319', 'countries_id' => '5', 'name' => json_encode(['ar' => 'دهوك', 'en' => 'Duhok'])],
            ['id' => '320', 'countries_id' => '5', 'name' => json_encode(['ar' => 'حلبجة', 'en' => 'Halabja'])],
            ['id' => '321', 'countries_id' => '5', 'name' => json_encode(['ar' => 'القادسية', 'en' => 'Qadisiyyah'])],
            ['id' => '322', 'countries_id' => '5', 'name' => json_encode(['ar' => 'سامراء', 'en' => 'Samarra'])],


            ['id' => '401', 'countries_id' => '6', 'name' => json_encode(['ar' => 'عمان', 'en' => 'Amman'])],
            ['id' => '402', 'countries_id' => '6', 'name' => json_encode(['ar' => 'الزرقاء', 'en' => 'Zarqa'])],
            ['id' => '403', 'countries_id' => '6', 'name' => json_encode(['ar' => 'إربد', 'en' => 'Irbid'])],
            ['id' => '404', 'countries_id' => '6', 'name' => json_encode(['ar' => 'العقبة', 'en' => 'Aqaba'])],
            ['id' => '405', 'countries_id' => '6', 'name' => json_encode(['ar' => 'السلط', 'en' => 'Salt'])],
            ['id' => '406', 'countries_id' => '6', 'name' => json_encode(['ar' => 'المفرق', 'en' => 'Mafraq'])],
            ['id' => '407', 'countries_id' => '6', 'name' => json_encode(['ar' => 'الكرك', 'en' => 'Karak'])],
            ['id' => '408', 'countries_id' => '6', 'name' => json_encode(['ar' => 'معان', 'en' => 'Maan'])],
            ['id' => '409', 'countries_id' => '6', 'name' => json_encode(['ar' => 'الطفيلة', 'en' => 'Tafilah'])],
            ['id' => '410', 'countries_id' => '6', 'name' => json_encode(['ar' => 'جرش', 'en' => 'Jerash'])],
            ['id' => '411', 'countries_id' => '6', 'name' => json_encode(['ar' => 'عجلون', 'en' => 'Ajloun'])],

            ['id' => '421', 'countries_id' => '7', 'name' => json_encode(['ar' => 'المنامة', 'en' => 'Manama'])],
            ['id' => '422', 'countries_id' => '7', 'name' => json_encode(['ar' => 'الرفاع', 'en' => 'Riffa'])],
            ['id' => '423', 'countries_id' => '7', 'name' => json_encode(['ar' => 'المحرق', 'en' => 'Muharraq'])],
            ['id' => '424', 'countries_id' => '7', 'name' => json_encode(['ar' => 'الحد', 'en' => 'Hidd'])],
            ['id' => '425', 'countries_id' => '7', 'name' => json_encode(['ar' => 'مدينة عيسى', 'en' => 'Isa Town'])],
            ['id' => '426', 'countries_id' => '7', 'name' => json_encode(['ar' => 'السنابس', 'en' => 'Sanabis'])],
            ['id' => '427', 'countries_id' => '7', 'name' => json_encode(['ar' => 'سترة', 'en' => 'Sitra'])],
            ['id' => '428', 'countries_id' => '7', 'name' => json_encode(['ar' => 'مدينة حمد', 'en' => 'Hamad Town'])],
            ['id' => '429', 'countries_id' => '7', 'name' => json_encode(['ar' => 'جد حفص', 'en' => 'Jid Hafs'])],
            ['id' => '430', 'countries_id' => '7', 'name' => json_encode(['ar' => 'الدراز', 'en' => 'Diraz'])],
            ['id' => '431', 'countries_id' => '7', 'name' => json_encode(['ar' => 'المالكية', 'en' => 'Al Malkiyah'])],
            ['id' => '432', 'countries_id' => '7', 'name' => json_encode(['ar' => 'بني جمرة', 'en' => 'Bani Jamra'])],
            ['id' => '433', 'countries_id' => '7', 'name' => json_encode(['ar' => 'البديع', 'en' => 'Budaiya'])],
            ['id' => '434', 'countries_id' => '7', 'name' => json_encode(['ar' => 'النويدرات', 'en' => 'Nuwaidrat'])],
            ['id' => '435', 'countries_id' => '7', 'name' => json_encode(['ar' => 'عالي', 'en' => 'Aali'])],
            ['id' => '436', 'countries_id' => '7', 'name' => json_encode(['ar' => 'البسيتين', 'en' => 'Busaiteen'])],
            ['id' => '437', 'countries_id' => '7', 'name' => json_encode(['ar' => 'عراد', 'en' => 'Arad'])],
            ['id' => '438', 'countries_id' => '7', 'name' => json_encode(['ar' => 'سار', 'en' => 'Saar'])],
            ['id' => '439', 'countries_id' => '7', 'name' => json_encode(['ar' => 'الجسرة', 'en' => 'Al Jasra'])],
            ['id' => '440', 'countries_id' => '7', 'name' => json_encode(['ar' => 'كرزكان', 'en' => 'Karzakan'])],

            ['id' => '609', 'countries_id' => '9', 'name' => json_encode(['ar' => 'دخان', 'en' => 'Dukhan'])],
            ['id' => '610', 'countries_id' => '9', 'name' => json_encode(['ar' => 'مسيعيد', 'en' => 'Mesaieed'])],
            ['id' => '608', 'countries_id' => '9', 'name' => json_encode(['ar' => 'الخيسة', 'en' => 'Al Kheesa'])],
            ['id' => '611', 'countries_id' => '9', 'name' => json_encode(['ar' => 'لوسيل', 'en' => 'Lusail'])],
            ['id' => '612', 'countries_id' => '9', 'name' => json_encode(['ar' => 'الذخيرة', 'en' => 'Al Thakhira'])],
            ['id' => '613', 'countries_id' => '9', 'name' => json_encode(['ar' => 'الرويس', 'en' => 'Al Ruwais'])],
            ['id' => '614', 'countries_id' => '9', 'name' => json_encode(['ar' => 'الجميلية', 'en' => 'Al Jumayliyah'])],
            ['id' => '615', 'countries_id' => '9', 'name' => json_encode(['ar' => 'الغويرية', 'en' => 'Al Ghuwariyah'])],
            ['id' => '616', 'countries_id' => '9', 'name' => json_encode(['ar' => 'الخور الشمالية', 'en' => 'Al Khor North'])],
            ['id' => '617', 'countries_id' => '9', 'name' => json_encode(['ar' => 'سميسمة', 'en' => 'Simaisma'])],
            ['id' => '618', 'countries_id' => '9', 'name' => json_encode(['ar' => 'الزبارة', 'en' => 'Al Zubarah'])],
            ['id' => '619', 'countries_id' => '9', 'name' => json_encode(['ar' => 'الوكير', 'en' => 'Al Wukair'])],
            ['id' => '620', 'countries_id' => '9', 'name' => json_encode(['ar' => 'حالول', 'en' => 'Halul Island'])],


            ['id' => '901', 'countries_id' => '14', 'name' => json_encode(['ar' => 'دمشق', 'en' => 'Damascus'])],
            ['id' => '902', 'countries_id' => '14', 'name' => json_encode(['ar' => 'حلب', 'en' => 'Aleppo'])],
            ['id' => '903', 'countries_id' => '14', 'name' => json_encode(['ar' => 'حمص', 'en' => 'Homs'])],
            ['id' => '904', 'countries_id' => '14', 'name' => json_encode(['ar' => 'حماة', 'en' => 'Hama'])],
            ['id' => '905', 'countries_id' => '14', 'name' => json_encode(['ar' => 'اللاذقية', 'en' => 'Latakia'])],
            ['id' => '906', 'countries_id' => '14', 'name' => json_encode(['ar' => 'طرطوس', 'en' => 'Tartus'])],
            ['id' => '907', 'countries_id' => '14', 'name' => json_encode(['ar' => 'دير الزور', 'en' => 'Deir ez-Zor'])],
            ['id' => '908', 'countries_id' => '14', 'name' => json_encode(['ar' => 'الرقة', 'en' => 'Raqqa'])],
            ['id' => '909', 'countries_id' => '14', 'name' => json_encode(['ar' => 'الحسكة', 'en' => 'Al-Hasakah'])],
            ['id' => '910', 'countries_id' => '14', 'name' => json_encode(['ar' => 'إدلب', 'en' => 'Idlib'])],
            ['id' => '911', 'countries_id' => '14', 'name' => json_encode(['ar' => 'السويداء', 'en' => 'As-Suwayda'])],
            ['id' => '912', 'countries_id' => '14', 'name' => json_encode(['ar' => 'القامشلي', 'en' => 'Qamishli'])],
            ['id' => '913', 'countries_id' => '14', 'name' => json_encode(['ar' => 'الميادين', 'en' => 'Al-Mayadin'])],
            ['id' => '914', 'countries_id' => '14', 'name' => json_encode(['ar' => 'البوكمال', 'en' => 'Abu Kamal'])],
            ['id' => '915', 'countries_id' => '14', 'name' => json_encode(['ar' => 'منبج', 'en' => 'Manbij'])],
            ['id' => '916', 'countries_id' => '14', 'name' => json_encode(['ar' => 'سلمية', 'en' => 'Salamiyah'])],
            ['id' => '917', 'countries_id' => '14', 'name' => json_encode(['ar' => 'جبلة', 'en' => 'Jableh'])],
            ['id' => '918', 'countries_id' => '14', 'name' => json_encode(['ar' => 'مصياف', 'en' => 'Masyaf'])],
            ['id' => '919', 'countries_id' => '14', 'name' => json_encode(['ar' => 'بانياس', 'en' => 'Baniyas'])],
            ['id' => '920', 'countries_id' => '14', 'name' => json_encode(['ar' => 'عفرين', 'en' => 'Afrin'])],
            ['id' => '921', 'countries_id' => '14', 'name' => json_encode(['ar' => 'التل', 'en' => 'Al-Tall'])],
            ['id' => '922', 'countries_id' => '14', 'name' => json_encode(['ar' => 'الرستن', 'en' => 'Ar-Rastan'])],
            ['id' => '923', 'countries_id' => '14', 'name' => json_encode(['ar' => 'مارع', 'en' => 'Marea'])],
            ['id' => '924', 'countries_id' => '14', 'name' => json_encode(['ar' => 'عين العرب', 'en' => 'Kobani'])],
            ['id' => '925', 'countries_id' => '14', 'name' => json_encode(['ar' => 'ازرع', 'en' => 'Izra'])],


            ['id' => '701', 'countries_id' => '16', 'name' => json_encode(['ar' => 'مدينة الكويت', 'en' => 'Kuwait City'])],
            ['id' => '702', 'countries_id' => '16', 'name' => json_encode(['ar' => 'حولي', 'en' => 'Hawalli'])],
            ['id' => '703', 'countries_id' => '16', 'name' => json_encode(['ar' => 'الفروانية', 'en' => 'Farwaniya'])],
            ['id' => '704', 'countries_id' => '16', 'name' => json_encode(['ar' => 'الأحمدي', 'en' => 'Ahmadi'])],
            ['id' => '705', 'countries_id' => '16', 'name' => json_encode(['ar' => 'الجهراء', 'en' => 'Jahra'])],
            ['id' => '706', 'countries_id' => '16', 'name' => json_encode(['ar' => 'صباح السالم', 'en' => 'Sabah Al-Salem'])],
            ['id' => '707', 'countries_id' => '16', 'name' => json_encode(['ar' => 'السالمية', 'en' => 'Salmiya'])],
            ['id' => '708', 'countries_id' => '16', 'name' => json_encode(['ar' => 'الفنطاس', 'en' => 'Al Fintas'])],
            ['id' => '709', 'countries_id' => '16', 'name' => json_encode(['ar' => 'المنقف', 'en' => 'Mangaf'])],
            ['id' => '710', 'countries_id' => '16', 'name' => json_encode(['ar' => 'الفحيحيل', 'en' => 'Fahaheel'])],
            ['id' => '711', 'countries_id' => '16', 'name' => json_encode(['ar' => 'الجهراء الجديدة', 'en' => 'New Jahra'])],
            ['id' => '712', 'countries_id' => '16', 'name' => json_encode(['ar' => 'ميناء عبدالله', 'en' => 'Mina Abdullah'])],
            ['id' => '713', 'countries_id' => '16', 'name' => json_encode(['ar' => 'صبحان', 'en' => 'Sabhan'])],
            ['id' => '714', 'countries_id' => '16', 'name' => json_encode(['ar' => 'الرقة', 'en' => 'Riqqa'])],
            ['id' => '715', 'countries_id' => '16', 'name' => json_encode(['ar' => 'القيروان', 'en' => 'Qairawan'])],
            ['id' => '716', 'countries_id' => '16', 'name' => json_encode(['ar' => 'العارضية', 'en' => 'Ardiya'])],
            ['id' => '717', 'countries_id' => '16', 'name' => json_encode(['ar' => 'الوفرة', 'en' => 'Wafra'])],
            ['id' => '718', 'countries_id' => '16', 'name' => json_encode(['ar' => 'الزور', 'en' => 'Al-Zour'])],


            ['id' => '801', 'countries_id' => '17', 'name' => json_encode(['ar' => 'بيروت', 'en' => 'Beirut'])],
            ['id' => '802', 'countries_id' => '17', 'name' => json_encode(['ar' => 'طرابلس', 'en' => 'Tripoli'])],
            ['id' => '803', 'countries_id' => '17', 'name' => json_encode(['ar' => 'صيدا', 'en' => 'Sidon'])],
            ['id' => '804', 'countries_id' => '17', 'name' => json_encode(['ar' => 'صور', 'en' => 'Tyre'])],
            ['id' => '805', 'countries_id' => '17', 'name' => json_encode(['ar' => 'زحلة', 'en' => 'Zahle'])],
            ['id' => '806', 'countries_id' => '17', 'name' => json_encode(['ar' => 'جونيه', 'en' => 'Jounieh'])],
            ['id' => '807', 'countries_id' => '17', 'name' => json_encode(['ar' => 'بعلبك', 'en' => 'Baalbek'])],
            ['id' => '808', 'countries_id' => '17', 'name' => json_encode(['ar' => 'النبطية', 'en' => 'Nabatieh'])],
            ['id' => '809', 'countries_id' => '17', 'name' => json_encode(['ar' => 'جبيل', 'en' => 'Byblos'])],
            ['id' => '810', 'countries_id' => '17', 'name' => json_encode(['ar' => 'صيدون', 'en' => 'Saida'])],
            ['id' => '811', 'countries_id' => '17', 'name' => json_encode(['ar' => 'جزين', 'en' => 'Jezzine'])],
            ['id' => '812', 'countries_id' => '17', 'name' => json_encode(['ar' => 'حلبا', 'en' => 'Halba'])],
            ['id' => '813', 'countries_id' => '17', 'name' => json_encode(['ar' => 'بشري', 'en' => 'Bsharri'])],
            ['id' => '814', 'countries_id' => '17', 'name' => json_encode(['ar' => 'البترون', 'en' => 'Batroun'])],
            ['id' => '815', 'countries_id' => '17', 'name' => json_encode(['ar' => 'عاليه', 'en' => 'Aley'])],
            ['id' => '817', 'countries_id' => '17', 'name' => json_encode(['ar' => 'المتن', 'en' => 'Matn'])],
            ['id' => '818', 'countries_id' => '17', 'name' => json_encode(['ar' => 'الهرمل', 'en' => 'Hermel'])],
            ['id' => '819', 'countries_id' => '17', 'name' => json_encode(['ar' => 'راشيا', 'en' => 'Rachaya'])],
            ['id' => '820', 'countries_id' => '17', 'name' => json_encode(['ar' => 'الشوف', 'en' => 'Chouf'])],

            //yemen
            ['id' => '501', 'countries_id' => '8', 'name' => json_encode(['ar' => 'صنعاء', 'en' => 'Sana\'a'])],
            ['id' => '502', 'countries_id' => '8', 'name' => json_encode(['ar' => 'عدن', 'en' => 'Aden'])],
            ['id' => '503', 'countries_id' => '8', 'name' => json_encode(['ar' => 'تعز', 'en' => 'Taiz'])],
            ['id' => '504', 'countries_id' => '8', 'name' => json_encode(['ar' => 'الحديدة', 'en' => 'Hodeidah'])],
            ['id' => '505', 'countries_id' => '8', 'name' => json_encode(['ar' => 'المكلا', 'en' => 'Mukalla'])],
            ['id' => '506', 'countries_id' => '8', 'name' => json_encode(['ar' => 'إب', 'en' => 'Ibb'])],
            ['id' => '507', 'countries_id' => '8', 'name' => json_encode(['ar' => 'ذمار', 'en' => 'Dhamar'])],
            ['id' => '508', 'countries_id' => '8', 'name' => json_encode(['ar' => 'البيضاء', 'en' => 'Al Bayda'])],
            ['id' => '509', 'countries_id' => '8', 'name' => json_encode(['ar' => 'حضرموت', 'en' => 'Hadhramaut'])],
            ['id' => '510', 'countries_id' => '8', 'name' => json_encode(['ar' => 'صعدة', 'en' => 'Saada'])],
            ['id' => '511', 'countries_id' => '8', 'name' => json_encode(['ar' => 'عمران', 'en' => 'Amran'])],
            ['id' => '512', 'countries_id' => '8', 'name' => json_encode(['ar' => 'حجة', 'en' => 'Hajjah'])],
            ['id' => '513', 'countries_id' => '8', 'name' => json_encode(['ar' => 'الضالع', 'en' => 'Ad Dali'])],
            ['id' => '514', 'countries_id' => '8', 'name' => json_encode(['ar' => 'لحج', 'en' => 'Lahij'])],
            ['id' => '515', 'countries_id' => '8', 'name' => json_encode(['ar' => 'مأرب', 'en' => 'Marib'])],
            ['id' => '516', 'countries_id' => '8', 'name' => json_encode(['ar' => 'أبين', 'en' => 'Abyan'])],
            ['id' => '517', 'countries_id' => '8', 'name' => json_encode(['ar' => 'شبوة', 'en' => 'Shabwah'])],
            ['id' => '518', 'countries_id' => '8', 'name' => json_encode(['ar' => 'الجوف', 'en' => 'Al Jawf'])],
            ['id' => '519', 'countries_id' => '8', 'name' => json_encode(['ar' => 'ريمة', 'en' => 'Raymah'])],
            ['id' => '520', 'countries_id' => '8', 'name' => json_encode(['ar' => 'سقطرى', 'en' => 'Socotra'])],
            ['id' => '521', 'countries_id' => '8', 'name' => json_encode(['ar' => 'المحويت', 'en' => 'Al Mahwit'])],
            ['id' => '522', 'countries_id' => '8', 'name' => json_encode(['ar' => 'زبيد', 'en' => 'Zabid'])],
            ['id' => '523', 'countries_id' => '8', 'name' => json_encode(['ar' => 'الغيضة', 'en' => 'Al Ghaydah'])],
            ['id' => '524', 'countries_id' => '8', 'name' => json_encode(['ar' => 'رداع', 'en' => 'Rada\'a'])],
            ['id' => '525', 'countries_id' => '8', 'name' => json_encode(['ar' => 'بيت الفقيه', 'en' => 'Bayt al-Faqih'])],

            //2. Algeria (ID: 10)
            ['id' => '1001', 'countries_id' => '10', 'name' => json_encode(['ar' => 'الجزائر', 'en' => 'Algiers'])],
            ['id' => '1002', 'countries_id' => '10', 'name' => json_encode(['ar' => 'وهران', 'en' => 'Oran'])],
            ['id' => '1003', 'countries_id' => '10', 'name' => json_encode(['ar' => 'قسنطينة', 'en' => 'Constantine'])],
            ['id' => '1004', 'countries_id' => '10', 'name' => json_encode(['ar' => 'عنابة', 'en' => 'Annaba'])],
            ['id' => '1005', 'countries_id' => '10', 'name' => json_encode(['ar' => 'باتنة', 'en' => 'Batna'])],
            ['id' => '1006', 'countries_id' => '10', 'name' => json_encode(['ar' => 'سطيف', 'en' => 'Setif'])],
            ['id' => '1007', 'countries_id' => '10', 'name' => json_encode(['ar' => 'سيدي بلعباس', 'en' => 'Sidi Bel Abbes'])],
            ['id' => '1008', 'countries_id' => '10', 'name' => json_encode(['ar' => 'تلمسان', 'en' => 'Tlemcen'])],
            ['id' => '1009', 'countries_id' => '10', 'name' => json_encode(['ar' => 'بسكرة', 'en' => 'Biskra'])],
            ['id' => '1010', 'countries_id' => '10', 'name' => json_encode(['ar' => 'بجاية', 'en' => 'Bejaia'])],
            ['id' => '1011', 'countries_id' => '10', 'name' => json_encode(['ar' => 'تيزي وزو', 'en' => 'Tizi Ouzou'])],
            ['id' => '1012', 'countries_id' => '10', 'name' => json_encode(['ar' => 'الشلف', 'en' => 'Chlef'])],
            ['id' => '1013', 'countries_id' => '10', 'name' => json_encode(['ar' => 'بليدة', 'en' => 'Blida'])],
            ['id' => '1014', 'countries_id' => '10', 'name' => json_encode(['ar' => 'برج بوعريريج', 'en' => 'Bordj Bou Arreridj'])],
            ['id' => '1015', 'countries_id' => '10', 'name' => json_encode(['ar' => 'سكيكدة', 'en' => 'Skikda'])],
            ['id' => '1016', 'countries_id' => '10', 'name' => json_encode(['ar' => 'المدية', 'en' => 'Medea'])],
            ['id' => '1017', 'countries_id' => '10', 'name' => json_encode(['ar' => 'المسيلة', 'en' => 'M\'Sila'])],
            ['id' => '1018', 'countries_id' => '10', 'name' => json_encode(['ar' => 'تيارت', 'en' => 'Tiaret'])],
            ['id' => '1019', 'countries_id' => '10', 'name' => json_encode(['ar' => 'غليزان', 'en' => 'Relizane'])],
            ['id' => '1020', 'countries_id' => '10', 'name' => json_encode(['ar' => 'الجلفة', 'en' => 'Djelfa'])],
            ['id' => '1021', 'countries_id' => '10', 'name' => json_encode(['ar' => 'مستغانم', 'en' => 'Mostaganem'])],
            ['id' => '1022', 'countries_id' => '10', 'name' => json_encode(['ar' => 'ورقلة', 'en' => 'Ouargla'])],
            ['id' => '1023', 'countries_id' => '10', 'name' => json_encode(['ar' => 'البويرة', 'en' => 'Bouira'])],
            ['id' => '1024', 'countries_id' => '10', 'name' => json_encode(['ar' => 'غرداية', 'en' => 'Ghardaia'])],
            ['id' => '1025', 'countries_id' => '10', 'name' => json_encode(['ar' => 'خنشلة', 'en' => 'Khenchela'])],
            ['id' => '1026', 'countries_id' => '10', 'name' => json_encode(['ar' => 'أدرار', 'en' => 'Adrar'])],
            ['id' => '1027', 'countries_id' => '10', 'name' => json_encode(['ar' => 'تندوف', 'en' => 'Tindouf'])],
            ['id' => '1028', 'countries_id' => '10', 'name' => json_encode(['ar' => 'الوادي', 'en' => 'El Oued'])],
            ['id' => '1029', 'countries_id' => '10', 'name' => json_encode(['ar' => 'الأغواط', 'en' => 'Laghouat'])],
            ['id' => '1030', 'countries_id' => '10', 'name' => json_encode(['ar' => 'عين تموشنت', 'en' => 'Ain Temouchent'])],


            //Morocco (ID: 11)
            ['id' => '1101', 'countries_id' => '11', 'name' => json_encode(['ar' => 'الرباط', 'en' => 'Rabat'])],
            ['id' => '1102', 'countries_id' => '11', 'name' => json_encode(['ar' => 'الدار البيضاء', 'en' => 'Casablanca'])],
            ['id' => '1103', 'countries_id' => '11', 'name' => json_encode(['ar' => 'فاس', 'en' => 'Fes'])],
            ['id' => '1104', 'countries_id' => '11', 'name' => json_encode(['ar' => 'مراكش', 'en' => 'Marrakesh'])],
            ['id' => '1105', 'countries_id' => '11', 'name' => json_encode(['ar' => 'طنجة', 'en' => 'Tangier'])],
            ['id' => '1106', 'countries_id' => '11', 'name' => json_encode(['ar' => 'أكادير', 'en' => 'Agadir'])],
            ['id' => '1107', 'countries_id' => '11', 'name' => json_encode(['ar' => 'مكناس', 'en' => 'Meknes'])],
            ['id' => '1108', 'countries_id' => '11', 'name' => json_encode(['ar' => 'وجدة', 'en' => 'Oujda'])],
            ['id' => '1109', 'countries_id' => '11', 'name' => json_encode(['ar' => 'القنيطرة', 'en' => 'Kenitra'])],
            ['id' => '1110', 'countries_id' => '11', 'name' => json_encode(['ar' => 'تطوان', 'en' => 'Tetouan'])],
            ['id' => '1111', 'countries_id' => '11', 'name' => json_encode(['ar' => 'آسفي', 'en' => 'Safi'])],
            ['id' => '1112', 'countries_id' => '11', 'name' => json_encode(['ar' => 'الجديدة', 'en' => 'El Jadida'])],
            ['id' => '1113', 'countries_id' => '11', 'name' => json_encode(['ar' => 'تازة', 'en' => 'Taza'])],
            ['id' => '1114', 'countries_id' => '11', 'name' => json_encode(['ar' => 'بني ملال', 'en' => 'Beni Mellal'])],
            ['id' => '1115', 'countries_id' => '11', 'name' => json_encode(['ar' => 'خريبكة', 'en' => 'Khouribga'])],
            ['id' => '1116', 'countries_id' => '11', 'name' => json_encode(['ar' => 'العرائش', 'en' => 'Larache'])],
            ['id' => '1117', 'countries_id' => '11', 'name' => json_encode(['ar' => 'الناظور', 'en' => 'Nador'])],
            ['id' => '1118', 'countries_id' => '11', 'name' => json_encode(['ar' => 'سطات', 'en' => 'Settat'])],
            ['id' => '1119', 'countries_id' => '11', 'name' => json_encode(['ar' => 'تمارة', 'en' => 'Temara'])],
            ['id' => '1120', 'countries_id' => '11', 'name' => json_encode(['ar' => 'الصويرة', 'en' => 'Essaouira'])],
            ['id' => '1121', 'countries_id' => '11', 'name' => json_encode(['ar' => 'العيون', 'en' => 'Laayoune'])],
            ['id' => '1122', 'countries_id' => '11', 'name' => json_encode(['ar' => 'الداخلة', 'en' => 'Dakhla'])],
            ['id' => '1123', 'countries_id' => '11', 'name' => json_encode(['ar' => 'خنيفرة', 'en' => 'Khenifra'])],
            ['id' => '1124', 'countries_id' => '11', 'name' => json_encode(['ar' => 'ورزازات', 'en' => 'Ouarzazate'])],
            ['id' => '1125', 'countries_id' => '11', 'name' => json_encode(['ar' => 'طاطا', 'en' => 'Tata'])],
            ['id' => '1126', 'countries_id' => '11', 'name' => json_encode(['ar' => 'طانطان', 'en' => 'Tan-Tan'])],
            ['id' => '1127', 'countries_id' => '11', 'name' => json_encode(['ar' => 'كلميم', 'en' => 'Guelmim'])],
            ['id' => '1128', 'countries_id' => '11', 'name' => json_encode(['ar' => 'الراشيدية', 'en' => 'Errachidia'])],
            ['id' => '1129', 'countries_id' => '11', 'name' => json_encode(['ar' => 'الحسيمة', 'en' => 'Al Hoceima'])],
            ['id' => '1130', 'countries_id' => '11', 'name' => json_encode(['ar' => 'تارودانت', 'en' => 'Taroudant'])],

            // Tunisia (ID: 12)
            ['id' => '1201', 'countries_id' => '12', 'name' => json_encode(['ar' => 'تونس', 'en' => 'Tunis'])],
            ['id' => '1202', 'countries_id' => '12', 'name' => json_encode(['ar' => 'صفاقس', 'en' => 'Sfax'])],
            ['id' => '1203', 'countries_id' => '12', 'name' => json_encode(['ar' => 'سوسة', 'en' => 'Sousse'])],
            ['id' => '1204', 'countries_id' => '12', 'name' => json_encode(['ar' => 'القيروان', 'en' => 'Kairouan'])],
            ['id' => '1205', 'countries_id' => '12', 'name' => json_encode(['ar' => 'بنزرت', 'en' => 'Bizerte'])],
            ['id' => '1206', 'countries_id' => '12', 'name' => json_encode(['ar' => 'قابس', 'en' => 'Gabes'])],
            ['id' => '1207', 'countries_id' => '12', 'name' => json_encode(['ar' => 'المنستير', 'en' => 'Monastir'])],
            ['id' => '1208', 'countries_id' => '12', 'name' => json_encode(['ar' => 'المهدية', 'en' => 'Mahdia'])],
            ['id' => '1209', 'countries_id' => '12', 'name' => json_encode(['ar' => 'نابل', 'en' => 'Nabeul'])],
            ['id' => '1210', 'countries_id' => '12', 'name' => json_encode(['ar' => 'جندوبة', 'en' => 'Jendouba'])],
            ['id' => '1211', 'countries_id' => '12', 'name' => json_encode(['ar' => 'باجة', 'en' => 'Beja'])],
            ['id' => '1212', 'countries_id' => '12', 'name' => json_encode(['ar' => 'قفصة', 'en' => 'Gafsa'])],
            ['id' => '1213', 'countries_id' => '12', 'name' => json_encode(['ar' => 'مدنين', 'en' => 'Medenine'])],
            ['id' => '1214', 'countries_id' => '12', 'name' => json_encode(['ar' => 'تطاوين', 'en' => 'Tataouine'])],
            ['id' => '1215', 'countries_id' => '12', 'name' => json_encode(['ar' => 'توزر', 'en' => 'Tozeur'])],
            ['id' => '1216', 'countries_id' => '12', 'name' => json_encode(['ar' => 'قبلي', 'en' => 'Kebili'])],
            ['id' => '1217', 'countries_id' => '12', 'name' => json_encode(['ar' => 'سليانة', 'en' => 'Siliana'])],
            ['id' => '1218', 'countries_id' => '12', 'name' => json_encode(['ar' => 'الكاف', 'en' => 'Le Kef'])],
            ['id' => '1219', 'countries_id' => '12', 'name' => json_encode(['ar' => 'القصرين', 'en' => 'Kasserine'])],
            ['id' => '1220', 'countries_id' => '12', 'name' => json_encode(['ar' => 'سيدي بوزيد', 'en' => 'Sidi Bouzid'])],
            ['id' => '1221', 'countries_id' => '12', 'name' => json_encode(['ar' => 'زغوان', 'en' => 'Zaghouan'])],
            ['id' => '1222', 'countries_id' => '12', 'name' => json_encode(['ar' => 'بن عروس', 'en' => 'Ben Arous'])],
            ['id' => '1223', 'countries_id' => '12', 'name' => json_encode(['ar' => 'أريانة', 'en' => 'Ariana'])],
            ['id' => '1224', 'countries_id' => '12', 'name' => json_encode(['ar' => 'منوبة', 'en' => 'Manouba'])],

            //Libya (ID: 13)
            ['id' => '1301', 'countries_id' => '13', 'name' => json_encode(['ar' => 'طرابلس', 'en' => 'Tripoli'])],
            ['id' => '1302', 'countries_id' => '13', 'name' => json_encode(['ar' => 'بنغازي', 'en' => 'Benghazi'])],
            ['id' => '1303', 'countries_id' => '13', 'name' => json_encode(['ar' => 'مصراتة', 'en' => 'Misrata'])],
            ['id' => '1304', 'countries_id' => '13', 'name' => json_encode(['ar' => 'الزاوية', 'en' => 'Zawiya'])],
            ['id' => '1305', 'countries_id' => '13', 'name' => json_encode(['ar' => 'سبها', 'en' => 'Sabha'])],
            ['id' => '1306', 'countries_id' => '13', 'name' => json_encode(['ar' => 'زليتن', 'en' => 'Zliten'])],
            ['id' => '1307', 'countries_id' => '13', 'name' => json_encode(['ar' => 'البيضاء', 'en' => 'Al Bayda'])],
            ['id' => '1308', 'countries_id' => '13', 'name' => json_encode(['ar' => 'طبرق', 'en' => 'Tobruk'])],
            ['id' => '1309', 'countries_id' => '13', 'name' => json_encode(['ar' => 'درنة', 'en' => 'Derna'])],
            ['id' => '1310', 'countries_id' => '13', 'name' => json_encode(['ar' => 'سرت', 'en' => 'Sirte'])],
            ['id' => '1311', 'countries_id' => '13', 'name' => json_encode(['ar' => 'الخمس', 'en' => 'Al Khums'])],
            ['id' => '1312', 'countries_id' => '13', 'name' => json_encode(['ar' => 'غريان', 'en' => 'Gharyan'])],
            ['id' => '1313', 'countries_id' => '13', 'name' => json_encode(['ar' => 'صبراتة', 'en' => 'Sabratha'])],
            ['id' => '1314', 'countries_id' => '13', 'name' => json_encode(['ar' => 'أجدابيا', 'en' => 'Ajdabiya'])],
            ['id' => '1315', 'countries_id' => '13', 'name' => json_encode(['ar' => 'مرزق', 'en' => 'Murzuk'])],
            ['id' => '1316', 'countries_id' => '13', 'name' => json_encode(['ar' => 'الجفرة', 'en' => 'Al Jufrah'])],
            ['id' => '1317', 'countries_id' => '13', 'name' => json_encode(['ar' => 'الكفرة', 'en' => 'Al Kufrah'])],
            ['id' => '1318', 'countries_id' => '13', 'name' => json_encode(['ar' => 'غدامس', 'en' => 'Ghadames'])],
            ['id' => '1319', 'countries_id' => '13', 'name' => json_encode(['ar' => 'ترهونة', 'en' => 'Tarhuna'])],
            ['id' => '1320', 'countries_id' => '13', 'name' => json_encode(['ar' => 'المرج', 'en' => 'Al Marj'])],
            ['id' => '1321', 'countries_id' => '13', 'name' => json_encode(['ar' => 'زوارة', 'en' => 'Zuwarah'])],
            ['id' => '1322', 'countries_id' => '13', 'name' => json_encode(['ar' => 'غات', 'en' => 'Ghat'])],

            //6. Sudan (ID: 15)
            ['id' => '1501', 'countries_id' => '15', 'name' => json_encode(['ar' => 'الخرطوم', 'en' => 'Khartoum'])],
            ['id' => '1502', 'countries_id' => '15', 'name' => json_encode(['ar' => 'أم درمان', 'en' => 'Omdurman'])],
            ['id' => '1503', 'countries_id' => '15', 'name' => json_encode(['ar' => 'بحري', 'en' => 'Bahri'])],
            ['id' => '1504', 'countries_id' => '15', 'name' => json_encode(['ar' => 'بورتسودان', 'en' => 'Port Sudan'])],
            ['id' => '1505', 'countries_id' => '15', 'name' => json_encode(['ar' => 'كسلا', 'en' => 'Kassala'])],
            ['id' => '1506', 'countries_id' => '15', 'name' => json_encode(['ar' => 'الأبيض', 'en' => 'El Obeid'])],
            ['id' => '1507', 'countries_id' => '15', 'name' => json_encode(['ar' => 'نيالا', 'en' => 'Nyala'])],
            ['id' => '1508', 'countries_id' => '15', 'name' => json_encode(['ar' => 'الفاشر', 'en' => 'El Fasher'])],
            ['id' => '1509', 'countries_id' => '15', 'name' => json_encode(['ar' => 'ود مدني', 'en' => 'Wad Madani'])],
            ['id' => '1510', 'countries_id' => '15', 'name' => json_encode(['ar' => 'الجنينة', 'en' => 'El Geneina'])],
            ['id' => '1511', 'countries_id' => '15', 'name' => json_encode(['ar' => 'الدمازين', 'en' => 'Ed Damazin'])],
            ['id' => '1512', 'countries_id' => '15', 'name' => json_encode(['ar' => 'سنار', 'en' => 'Sennar'])],
            ['id' => '1513', 'countries_id' => '15', 'name' => json_encode(['ar' => 'عطبرة', 'en' => 'Atbara'])],
            ['id' => '1514', 'countries_id' => '15', 'name' => json_encode(['ar' => 'كادقلي', 'en' => 'Kadugli'])],
            ['id' => '1515', 'countries_id' => '15', 'name' => json_encode(['ar' => 'كوستي', 'en' => 'Kosti'])],
            ['id' => '1516', 'countries_id' => '15', 'name' => json_encode(['ar' => 'الدويم', 'en' => 'Ed Dueim'])],
            ['id' => '1517', 'countries_id' => '15', 'name' => json_encode(['ar' => 'الرهد', 'en' => 'Er Rahad'])],
            ['id' => '1518', 'countries_id' => '15', 'name' => json_encode(['ar' => 'ربك', 'en' => 'Rabak'])],
            ['id' => '1519', 'countries_id' => '15', 'name' => json_encode(['ar' => 'بربر', 'en' => 'Berber'])],
            ['id' => '1520', 'countries_id' => '15', 'name' => json_encode(['ar' => 'حلفا الجديدة', 'en' => 'Halfa Al Jadeedah'])],
            ['id' => '1521', 'countries_id' => '15', 'name' => json_encode(['ar' => 'شندي', 'en' => 'Shendi'])],
            ['id' => '1522', 'countries_id' => '15', 'name' => json_encode(['ar' => 'القضارف', 'en' => 'Al Qadarif'])],
            ['id' => '1523', 'countries_id' => '15', 'name' => json_encode(['ar' => 'سواكن', 'en' => 'Suakin'])],
            ['id' => '1524', 'countries_id' => '15', 'name' => json_encode(['ar' => 'دنقلا', 'en' => 'Dongola'])],
            ['id' => '1525', 'countries_id' => '15', 'name' => json_encode(['ar' => 'حلفا', 'en' => 'Wadi Halfa'])],


            //7. Oman (ID: 18)
            ['id' => '1801', 'countries_id' => '18', 'name' => json_encode(['ar' => 'مسقط', 'en' => 'Muscat'])],
            ['id' => '1802', 'countries_id' => '18', 'name' => json_encode(['ar' => 'صلالة', 'en' => 'Salalah'])],
            ['id' => '1803', 'countries_id' => '18', 'name' => json_encode(['ar' => 'صحار', 'en' => 'Sohar'])],
            ['id' => '1804', 'countries_id' => '18', 'name' => json_encode(['ar' => 'نزوى', 'en' => 'Nizwa'])],
            ['id' => '1805', 'countries_id' => '18', 'name' => json_encode(['ar' => 'صور', 'en' => 'Sur'])],
            ['id' => '1806', 'countries_id' => '18', 'name' => json_encode(['ar' => 'البريمي', 'en' => 'Al Buraimi'])],
            ['id' => '1807', 'countries_id' => '18', 'name' => json_encode(['ar' => 'عبري', 'en' => 'Ibri'])],
            ['id' => '1808', 'countries_id' => '18', 'name' => json_encode(['ar' => 'بهلاء', 'en' => 'Bahla'])],
            ['id' => '1809', 'countries_id' => '18', 'name' => json_encode(['ar' => 'الرستاق', 'en' => 'Rustaq'])],
            ['id' => '1810', 'countries_id' => '18', 'name' => json_encode(['ar' => 'مطرح', 'en' => 'Matrah'])],
            ['id' => '1811', 'countries_id' => '18', 'name' => json_encode(['ar' => 'بركاء', 'en' => 'Barka'])],
            ['id' => '1812', 'countries_id' => '18', 'name' => json_encode(['ar' => 'السيب', 'en' => 'As Seeb'])],
            ['id' => '1813', 'countries_id' => '18', 'name' => json_encode(['ar' => 'صحم', 'en' => 'Saham'])],
            ['id' => '1814', 'countries_id' => '18', 'name' => json_encode(['ar' => 'شناص', 'en' => 'Shinas'])],
            ['id' => '1815', 'countries_id' => '18', 'name' => json_encode(['ar' => 'خصب', 'en' => 'Khasab'])],
            ['id' => '1816', 'countries_id' => '18', 'name' => json_encode(['ar' => 'مصيرة', 'en' => 'Masirah'])],
            ['id' => '1817', 'countries_id' => '18', 'name' => json_encode(['ar' => 'الخابورة', 'en' => 'Al Khaburah'])],
            ['id' => '1818', 'countries_id' => '18', 'name' => json_encode(['ar' => 'المصنعة', 'en' => 'Al Musannah'])],
            ['id' => '1819', 'countries_id' => '18', 'name' => json_encode(['ar' => 'السويق', 'en' => 'Al Suwaiq'])],
            ['id' => '1820', 'countries_id' => '18', 'name' => json_encode(['ar' => 'المضيبي', 'en' => 'Al Mudaybi'])],
            ['id' => '1821', 'countries_id' => '18', 'name' => json_encode(['ar' => 'إبراء', 'en' => 'Ibra'])],
            ['id' => '1822', 'countries_id' => '18', 'name' => json_encode(['ar' => 'ضنك', 'en' => 'Dhank'])],
            ['id' => '1823', 'countries_id' => '18', 'name' => json_encode(['ar' => 'أدم', 'en' => 'Adam'])],
            ['id' => '1824', 'countries_id' => '18', 'name' => json_encode(['ar' => 'محوت', 'en' => 'Mahout'])],


            //8. Mauritania (ID: 19)
            ['id' => '1901', 'countries_id' => '19', 'name' => json_encode(['ar' => 'نواكشوط', 'en' => 'Nouakchott'])],
            ['id' => '1902', 'countries_id' => '19', 'name' => json_encode(['ar' => 'نواذيبو', 'en' => 'Nouadhibou'])],
            ['id' => '1903', 'countries_id' => '19', 'name' => json_encode(['ar' => 'كيفة', 'en' => 'Kiffa'])],
            ['id' => '1904', 'countries_id' => '19', 'name' => json_encode(['ar' => 'روصو', 'en' => 'Rosso'])],
            ['id' => '1905', 'countries_id' => '19', 'name' => json_encode(['ar' => 'أطار', 'en' => 'Atar'])],
            ['id' => '1906', 'countries_id' => '19', 'name' => json_encode(['ar' => 'زويرات', 'en' => 'Zouerate'])],
            ['id' => '1907', 'countries_id' => '19', 'name' => json_encode(['ar' => 'كاراك', 'en' => 'Kaedi'])],
            ['id' => '1908', 'countries_id' => '19', 'name' => json_encode(['ar' => 'سيليبابي', 'en' => 'Selibaby'])],
            ['id' => '1909', 'countries_id' => '19', 'name' => json_encode(['ar' => 'بوتلميت', 'en' => 'Boutilimit'])],
            ['id' => '1910', 'countries_id' => '19', 'name' => json_encode(['ar' => 'تجكجة', 'en' => 'Tidjikja'])],
            ['id' => '1911', 'countries_id' => '19', 'name' => json_encode(['ar' => 'نعمة', 'en' => 'Nema'])],
            ['id' => '1912', 'countries_id' => '19', 'name' => json_encode(['ar' => 'العيون', 'en' => 'Ayoun el Atrous'])],
            ['id' => '1913', 'countries_id' => '19', 'name' => json_encode(['ar' => 'أكجوجت', 'en' => 'Akjoujt'])],
            ['id' => '1914', 'countries_id' => '19', 'name' => json_encode(['ar' => 'ألاك', 'en' => 'Aleg'])],
            ['id' => '1915', 'countries_id' => '19', 'name' => json_encode(['ar' => 'واد الناقة', 'en' => 'Oualata'])],
            ['id' => '1916', 'countries_id' => '19', 'name' => json_encode(['ar' => 'باركيول', 'en' => 'Barkeol'])],
            ['id' => '1917', 'countries_id' => '19', 'name' => json_encode(['ar' => 'شنقيط', 'en' => 'Chinguetti'])],
            ['id' => '1918', 'countries_id' => '19', 'name' => json_encode(['ar' => 'المجرية', 'en' => 'Magta Lahjar'])],
            ['id' => '1919', 'countries_id' => '19', 'name' => json_encode(['ar' => 'كوبني', 'en' => 'Kobenni'])],
            ['id' => '1920', 'countries_id' => '19', 'name' => json_encode(['ar' => 'تامشكط', 'en' => 'Tamchakett'])],

            //9. Somalia (ID: 20)
            ['id' => '2001', 'countries_id' => '20', 'name' => json_encode(['ar' => 'مقديشو', 'en' => 'Mogadishu'])],
            ['id' => '2002', 'countries_id' => '20', 'name' => json_encode(['ar' => 'هرجيسا', 'en' => 'Hargeisa'])],
            ['id' => '2003', 'countries_id' => '20', 'name' => json_encode(['ar' => 'بوساسو', 'en' => 'Bosaso'])],
            ['id' => '2004', 'countries_id' => '20', 'name' => json_encode(['ar' => 'كيسمايو', 'en' => 'Kismayo'])],
            ['id' => '2005', 'countries_id' => '20', 'name' => json_encode(['ar' => 'بربرة', 'en' => 'Berbera'])],
            ['id' => '2006', 'countries_id' => '20', 'name' => json_encode(['ar' => 'بيدوا', 'en' => 'Baidoa'])],
            ['id' => '2007', 'countries_id' => '20', 'name' => json_encode(['ar' => 'مركا', 'en' => 'Marka'])],
            ['id' => '2008', 'countries_id' => '20', 'name' => json_encode(['ar' => 'جالكعيو', 'en' => 'Galkayo'])],
            ['id' => '2009', 'countries_id' => '20', 'name' => json_encode(['ar' => 'بلدوين', 'en' => 'Beledweyne'])],
            ['id' => '2010', 'countries_id' => '20', 'name' => json_encode(['ar' => 'بوراما', 'en' => 'Borama'])],
            ['id' => '2011', 'countries_id' => '20', 'name' => json_encode(['ar' => 'جوهر', 'en' => 'Jowhar'])],
            ['id' => '2012', 'countries_id' => '20', 'name' => json_encode(['ar' => 'لاس عانود', 'en' => 'Las Anod'])],
            ['id' => '2013', 'countries_id' => '20', 'name' => json_encode(['ar' => 'غاروي', 'en' => 'Garowe'])],
            ['id' => '2014', 'countries_id' => '20', 'name' => json_encode(['ar' => 'عيريغابو', 'en' => 'Erigabo'])],
            ['id' => '2015', 'countries_id' => '20', 'name' => json_encode(['ar' => 'بلدوين', 'en' => 'Baardheere'])],
            ['id' => '2016', 'countries_id' => '20', 'name' => json_encode(['ar' => 'أفغويي', 'en' => 'Afgooye'])],
            ['id' => '2017', 'countries_id' => '20', 'name' => json_encode(['ar' => 'قردو', 'en' => 'Qardho'])],
            ['id' => '2018', 'countries_id' => '20', 'name' => json_encode(['ar' => 'ديرداب', 'en' => 'Dhuusa Mareeb'])],
            ['id' => '2019', 'countries_id' => '20', 'name' => json_encode(['ar' => 'بوهوتل', 'en' => 'Buhodle'])],
            ['id' => '2020', 'countries_id' => '20', 'name' => json_encode(['ar' => 'بعدويني', 'en' => 'Badweyn'])],
            ['id' => '2021', 'countries_id' => '20', 'name' => json_encode(['ar' => 'بركو', 'en' => 'Burtinle'])],
            ['id' => '2022', 'countries_id' => '20', 'name' => json_encode(['ar' => 'عدادو', 'en' => 'Adadle'])],
            ['id' => '2023', 'countries_id' => '20', 'name' => json_encode(['ar' => 'لوق', 'en' => 'Luuq'])],
            ['id' => '2024', 'countries_id' => '20', 'name' => json_encode(['ar' => 'بورعانود', 'en' => 'Burao'])],
        ];
        foreach ($cities as $city) {
            $subCategoryData = cities::create([
                'id' => $city['id'],
                'name' => $city['name'],
                'country_id' => $city['countries_id'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
            $subCategoryData->save();
        }
    }
}
