<?php

namespace Database\Seeders;

use App\Models\Photos;
use App\Models\sub_categories;
use Carbon\Carbon;

use Illuminate\Database\Seeder;


class subcategories extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    function run()
    {
        $subCategories = [
            ['id' => '1','categories_id' => '3','name' => 'أراضي', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/earth.png',],
            ['id' => '2','categories_id' => '3','name' => 'استديو', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/Studiohouse.png',],
             ['id' => '3','categories_id' => '3','name' => 'بيت شعبي', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/housepopular.png',],
             ['id' => '4','categories_id' => '3','name' => 'سكن عمال', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/accommodation.png',],
             ['id' => '5','categories_id' => '3','name' => 'شاليهات', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/chalets.png',],
             ['id' => '7','categories_id' => '3','name' => 'شقق', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/Apartments.png',],
             ['id' => '217','categories_id' => '3','name' => 'شقق مفروشة', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/apartmentground.jpg',],
             ['id' => '8','categories_id' => '3','name' => 'دولية', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/Internationalestate.png',],
             ['id' => '9','categories_id' => '3','name' => 'عمارات ومباني', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/condominium.png',],
             ['id' => '10','categories_id' => '3','name' => 'فلل ومنازل', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/villa.png',],
             ['id' => '11','categories_id' => '3','name' => 'فنادق ومنتجعات', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/hotel.png',],
             ['id' => '12','categories_id' => '3','name' => 'قاعات', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/Eventhalls.png',],
             ['id' => '13','categories_id' => '3','name' => 'قيد الانشاء', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/Excavatorconstruction.png',],
             ['id' => '14','categories_id' => '3','name' => 'مجمعات تجارية', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/shoppingmall.jpg',],
             ['id' => '15','categories_id' => '3','name' => 'محلات', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/retailstore.png',],
             ['id' => '16','categories_id' => '3','name' => 'مزارع', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/farmanimals.png',],
             ['id' => '17','categories_id' => '3','name' => 'مستودعات', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/warehouses.png',],
             ['id' => '18','categories_id' => '3','name' => 'مشاركة سكن', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/housingsharing.png',],
             ['id' => '19','categories_id' => '3','name' => 'مصانع', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/Factories.jpg',],
             ['id' => '20','categories_id' => '3','name' => 'مطاعم ومقاهي', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/Restaurants.png',],
             ['id' => '21','categories_id' => '3','name' => 'مكاتب', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/offices.png',],
             ['id' => '22','categories_id' => '3','name' => 'متفرقات', 'category_name' => 'عقارات','src' => 'storage/subcategory/عقارات/houseapartment.png',],
             ['id' => '23','categories_id' => '4','name' => 'استيراد سيارات', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/job.png',],
             ['id' => '24','categories_id' => '4','name' => 'قطاع غيار', 'category_name' => 'سيارات','src' => 'storage/subcategory/خدمات/maintenancess.png',],
             ['id' => '25','categories_id' => '4','name' => 'خدمات السيارات', 'category_name' => 'سيارات','src' => 'storage/subcategory/خدمات/carrepair.png',],
             ['id' => '26','categories_id' => '4','name' => 'اكسسورات', 'category_name' => 'سيارات','src' => 'storage/subcategory/خدمات/maintenancess.png',],
             ['id' => '27','categories_id' => '4','name' => 'تاجير', 'category_name' => 'سيارات','src' => 'storage/subcategory/خدمات/carrent.png',],
             ['id' => '28','categories_id' => '4','name' => 'ارقام', 'category_name' => 'سيارات','src' => 'storage/subcategory/خدمات/racingnumber.png',],
             ['id' => '160','categories_id' => '4','name' => 'دراجات نارية', 'category_name' => 'سيارات','src' => 'storage/subcategory/خدمات/Motorcycles.png',],
             ['id' => '29','categories_id' => '4','name' => 'استون مارتن', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/aston_martin.png',],
             ['id' => '30','categories_id' => '4','name' => 'اسيا', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/asia.png',],
             ['id' => '31','categories_id' => '4','name' => 'الفا روميو', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/alpha_Romeo.png',],
             ['id' => '32','categories_id' => '4','name' => 'ام جي', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/mg.png',],
             ['id' => '33','categories_id' => '4','name' => 'انفينيتي', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/infiniti.png',],
             ['id' => '34','categories_id' => '4','name' => 'اوبل', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/opel.png',],
             ['id' => '35','categories_id' => '4','name' => 'اودي', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/audi.png',],
             ['id' => '36','categories_id' => '4','name' => 'اوستن', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/Austin.png',],
             ['id' => '37','categories_id' => '4','name' => 'اولدس موبيل', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/Oldsmobile.png',],
             ['id' => '38','categories_id' => '4','name' => 'ايسوزي', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/isuzu.png',],
             ['id' => '39','categories_id' => '4','name' => 'بروتن', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/proton.png',],
             ['id' => '40','categories_id' => '4','name' => 'بليموث', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/Plymouth.png',],
             ['id' => '41','categories_id' => '4','name' => 'بنتلي', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/bentley.png',],
             ['id' => '42','categories_id' => '4','name' => 'بورش', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/porsche.png',],
             ['id' => '43','categories_id' => '4','name' => 'بوغاتي', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/Bugatti.png',],
             ['id' => '44','categories_id' => '4','name' => 'بويك', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/buick.png',],
             ['id' => '45','categories_id' => '4','name' => 'بي ام دبليو', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/bmw.png',],
             ['id' => '46','categories_id' => '4','name' => 'بيجو', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/Peugeot.png',],
             ['id' => '47','categories_id' => '4','name' => 'تاتا', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/Tata.png',],
             ['id' => '48','categories_id' => '4','name' => 'تويوتا', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/toyota.png',],
             ['id' => '49','categories_id' => '4','name' => 'جاك', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/JAC.png',],
             ['id' => '50','categories_id' => '4','name' => 'جاكوار', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/jaguar.png',],
             ['id' => '51','categories_id' => '4','name' => 'جي ام سي', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/gmc.png',],
             ['id' => '52','categories_id' => '4','name' => 'جيب', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/jeep.png',],
             ['id' => '53','categories_id' => '4','name' => 'داتسون', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/datsun.png',],
             ['id' => '54','categories_id' => '4','name' => 'داسيا', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/Dacia.png',],
             ['id' => '55','categories_id' => '4','name' => 'دايهاتسو', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/daihatsu.png',],
             ['id' => '56','categories_id' => '4','name' => 'دايوو', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/daewoo.png',],
             ['id' => '57','categories_id' => '4','name' => 'دفسك', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/dfsk.png',],
             ['id' => '58','categories_id' => '4','name' => 'دودج', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/dodge.png',],
             ['id' => '59','categories_id' => '4','name' => 'روفر', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/rover.png',],
             ['id' => '60','categories_id' => '4','name' => 'رولز رويس', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/rollsroyce.png',],
             ['id' => '61','categories_id' => '4','name' => 'رينو', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/renault.png',],
             ['id' => '62','categories_id' => '4','name' => 'ساب', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/Saab.png',],
             ['id' => '63','categories_id' => '4','name' => 'سابا', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/saba.png',],
             ['id' => '64','categories_id' => '4','name' => 'سانغيونغ', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/ssangyong.png',],
             ['id' => '65','categories_id' => '4','name' => 'ستروين', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/citroen.png',],
             ['id' => '66','categories_id' => '4','name' => 'سكودا', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/skoda.png',],
             ['id' => '67','categories_id' => '4','name' => 'سمارت', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/smart.png',],
             ['id' => '68','categories_id' => '4','name' => 'سوبارو', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/subaru.png',],
             ['id' => '69','categories_id' => '4','name' => 'سوزوكي', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/suzuki.png',],
             ['id' => '70','categories_id' => '4','name' => 'سيات', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/seat.png',],
             ['id' => '71','categories_id' => '4','name' => 'سيمكا', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/simca.png',],
             ['id' => '72','categories_id' => '4','name' => 'شفروليه', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/chevrolet.png',],
             ['id' => '73','categories_id' => '4','name' => 'شيري', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/chery.png',],
             ['id' => '74','categories_id' => '4','name' => 'فراري', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/ferrari.png',],
             ['id' => '75','categories_id' => '4','name' => 'فورد', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/ford.png',],
             ['id' => '76','categories_id' => '4','name' => 'فولفو', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/Volvo.png',],
             ['id' => '77','categories_id' => '4','name' => 'فولكس واجن', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/volkswagen.png',],
             ['id' => '78','categories_id' => '4','name' => 'فيات', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/fiat.png',],
             ['id' => '79','categories_id' => '4','name' => 'كاديلاك', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/cadillac.png',],
             ['id' => '80','categories_id' => '4','name' => 'كرايسلر', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/chrysler.png',],
             ['id' => '81','categories_id' => '4','name' => 'كلاسيكية', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/classic.png',],
             ['id' => '82','categories_id' => '4','name' => 'كيا', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/kia.png',],
             ['id' => '83','categories_id' => '4','name' => 'لادا', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/lada.png',],
             ['id' => '84','categories_id' => '4','name' => 'لامبرغيتي', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/lamborghini.png',],
             ['id' => '85','categories_id' => '4','name' => 'لاند روفر', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/landrover.png',],
             ['id' => '86','categories_id' => '4','name' => 'لانسيا', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/lancia.png',],
             ['id' => '87','categories_id' => '4','name' => 'لكزس', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/lexus.png',],
             ['id' => '88','categories_id' => '4','name' => 'لينكولن', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/lincoln.png',],
             ['id' => '89','categories_id' => '4','name' => 'مازدا', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/Mazda.png',],
             ['id' => '90','categories_id' => '4','name' => 'مازيراتي', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/maserati.png',],
             ['id' => '91','categories_id' => '4','name' => 'ماكلارين', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/Mclaren.png',],
             ['id' => '92','categories_id' => '4','name' => 'مرسيدس', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/mercedes.png',],
             ['id' => '93','categories_id' => '4','name' => 'مورغان', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/morgan.png',],
             ['id' => '94','categories_id' => '4','name' => 'ميتسوبيشي', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/mitsubishi.png',],
             ['id' => '95','categories_id' => '4','name' => 'ميركيري', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/Mercury.png',],
             ['id' => '96','categories_id' => '4','name' => 'ميني كوبر', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/minicooper.png',],
             ['id' => '97','categories_id' => '4','name' => 'نيسان', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/nissan.png',],
             ['id' => '98','categories_id' => '4','name' => 'همر', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/Hummer.png',],
             ['id' => '99','categories_id' => '4','name' => 'هوندا', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/honda.png',],
             ['id' => '100','categories_id' => '4','name' => 'هيونداي', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/hyundai.png',],
             ['id' => '101','categories_id' => '4','name' => 'متفرقات', 'category_name' => 'سيارات','src' => 'storage/subcategory/سيارات/general.png',],
             ['id' => '102','categories_id' => '1','name' => 'إدارة', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/businessperson.png',],
             ['id' => '103','categories_id' => '1','name' => 'أزياء', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/fashion.png',],
             ['id' => '104','categories_id' => '1','name' => 'برمجة', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/programmer.png',],
             ['id' => '105','categories_id' => '1','name' => 'تزيين وتجميل', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/salon.png',],
             ['id' => '106','categories_id' => '1','name' => 'تصميم', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/Design.png',],
             ['id' => '107','categories_id' => '1','name' => 'تعليم وتدريس', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/learning.png',],
             ['id' => '108','categories_id' => '1','name' => 'تقني', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/techengineering.png',],
             ['id' => '109','categories_id' => '1','name' => 'حدائق ومناظر', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/Garden.png',],
             ['id' => '110','categories_id' => '1','name' => 'حراسة وامن', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/securityguard.png',],
             ['id' => '111','categories_id' => '1','name' => 'حرفيين', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/profession.png',],
             ['id' => '112','categories_id' => '1','name' => 'محاسبة', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/accounting.png',],
             ['id' => '113','categories_id' => '1','name' => 'حضانة أطفال', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/childcare.png',],
             ['id' => '114','categories_id' => '1','name' => 'خدمة الزبائن', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/customercare.png',],
             ['id' => '115','categories_id' => '1','name' => 'خياطين', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/Tailors.png',],
             ['id' => '116','categories_id' => '1','name' => 'سائق', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/partybus.png',],
             ['id' => '117','categories_id' => '1','name' => 'سكرتارية', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/secretary.png',],
             ['id' => '118','categories_id' => '1','name' => 'سياحة وسفر', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/plane.png',],
             ['id' => '119','categories_id' => '1','name' => 'سياحة ومطاعم', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/Restaurant.png',],
             ['id' => '120','categories_id' => '1','name' => 'شراكة', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/copartnership.png',],
             ['id' => '121','categories_id' => '1','name' => 'طب وتمريض', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/Medicine.png',],
             ['id' => '122','categories_id' => '1','name' => 'علاقات عامة', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/publicrelations.png',],
             ['id' => '123','categories_id' => '1','name' => 'عمال', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/Workers.png',],
             ['id' => '124','categories_id' => '1','name' => 'عمال تنظيف', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/cleaning.png',],
             ['id' => '125','categories_id' => '1','name' => 'عمال ديلفري', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/delivery.png',],
             ['id' => '126','categories_id' => '1','name' => 'عمالة منزلية', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/homecleaning.png',],
             ['id' => '127','categories_id' => '1','name' => 'فنون جميلة', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/paintbrush.png',],
             ['id' => '128','categories_id' => '1','name' => 'كمبيوتر وشبكات', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/network.png',],
             ['id' => '129','categories_id' => '1','name' => 'لياقة بدنية', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/gym.png',],
             ['id' => '130','categories_id' => '1','name' => 'مبيعات وتسويق', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/marketing.png',],
             ['id' => '131','categories_id' => '1','name' => 'مترجمين', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/Translation.png',],
             ['id' => '132','categories_id' => '1','name' => 'محاماه وقانون', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/lawyer.png',],
             ['id' => '133','categories_id' => '1','name' => 'محررين', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/editing.png',],
             ['id' => '134','categories_id' => '1','name' => 'مدخل بيانات', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/dataentry.png',],
             ['id' => '135','categories_id' => '1','name' => 'مقاولات', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/Construction.png',],
             ['id' => '136','categories_id' => '1','name' => 'مهندس', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/Engineer.png',],
             ['id' => '137','categories_id' => '1','name' => 'موظفين', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/employees.png',],
             ['id' => '138','categories_id' => '1','name' => 'مونتاج وإخراج', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/videography.png',],
             ['id' => '139','categories_id' => '1','name' => 'متفرقات', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/job.png',],
             ['id' => '140','categories_id' => '5','name' => 'اتصالات', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/communication.png',],
             ['id' => '141','categories_id' => '5','name' => 'ارقام مميزة', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/numberstar.png',],
             ['id' => '142','categories_id' => '5','name' => 'اعمال واستثمار', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/investor.png',],
             ['id' => '143','categories_id' => '5','name' => 'اكسسورات', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/queen.png',],
             ['id' => '218','categories_id' => '5','name' => 'صرافة', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/investor.png',],
             ['id' => '219','categories_id' => '5','name' => 'سياحة وسفر', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/plane.png',],
             ['id' => '144','categories_id' => '5','name' => 'العاب', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/games.png',],
             ['id' => '145','categories_id' => '5','name' => 'الكترونيات', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/electronics.png',],
             ['id' => '146','categories_id' => '5','name' => 'اليات ثقيلة', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/heavy.png',],
             ['id' => '147','categories_id' => '5','name' => 'أنشطة', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/activity.png',],
             ['id' => '148','categories_id' => '5','name' => 'امن وحماية', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/camera.png',],
             ['id' => '149','categories_id' => '5','name' => 'بيت متنقل', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/pngtree.png',],
             ['id' => '150','categories_id' => '5','name' => 'تجهيز وتشطيب', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/silhouette.png',],
             ['id' => '151','categories_id' => '5','name' => 'تحف ومقتنيات', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/decoration.png',],
             ['id' => '152','categories_id' => '5','name' => 'تخليص معاملات', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/businessman.png',],
             ['id' => '153','categories_id' => '5','name' => 'تراخيص', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/license.png',],
             ['id' => '154','categories_id' => '5','name' => 'توصيل ونقل', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/truck.png',],
             ['id' => '155','categories_id' => '5','name' => 'حواسيب وصيانة', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/maintenance.png',],
             ['id' => '156','categories_id' => '5','name' => 'حيوانات', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/Pets.png',],
             ['id' => '157','categories_id' => '5','name' => 'خدمات الصيانة', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/maintenancess.png',],
             ['id' => '158','categories_id' => '5','name' => 'خدمات زراعية', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/agriculture.png',],
             ['id' => '159','categories_id' => '5','name' => 'خدمات عقارية', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/building.png',],
              ['id' => '161','categories_id' => '5','name' => 'ساعات', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/watch.png',],
             ['id' => '162','categories_id' => '5','name' => 'شحن', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/shipping.png',],
             ['id' => '163','categories_id' => '5','name' => 'صيد سمك', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/fishing.png',],
             ['id' => '164','categories_id' => '5','name' => 'طبخ منزلي', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/cooking.png',],
             ['id' => '165','categories_id' => '5','name' => 'عروض بالجملة', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/offers.png',],
             ['id' => '166','categories_id' => '5','name' => 'عطورات', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/parfume.png',],
             ['id' => '167','categories_id' => '5','name' => 'كتب ومجلات', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/Books.png',],
             ['id' => '168','categories_id' => '5','name' => 'مستحضرات تجميل', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/skincare.png',],
             ['id' => '169','categories_id' => '5','name' => 'معدات بحرية', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/maritime.png',],
             ['id' => '170','categories_id' => '5','name' => 'معدات رياضية', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/sportds.png',],
             ['id' => '171','categories_id' => '5','name' => 'مفروشات', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/Furnitures.png',],
             ['id' => '172','categories_id' => '5','name' => 'مفقودات', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/miscellaneous.png',],
             ['id' => '173','categories_id' => '5','name' => 'ملابس', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/clothes.png',],
             ['id' => '174','categories_id' => '5','name' => 'مواد بناء', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/renovation.png',],
             ['id' => '175','categories_id' => '5','name' => 'مواد غذائية', 'category_name' => 'خدمات','src' => 'storage/subcategory/خدمات/Goodfood.png',],
             ['id' => '176','categories_id' => '2','name' => 'مولدات كهرباء', 'category_name' => 'اجهزة','src' => 'storage/subcategory/خدمات/Generators.jpeg',],
             ['id' => '177','categories_id' => '2','name' => 'هواتف ذكية', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/phones.png',],
             ['id' => '178','categories_id' => '2','name' => 'كاميرات', 'category_name' => 'اجهزة','src' => 'storage/subcategory/خدمات/camerapencil.png',],
             ['id' => '179','categories_id' => '2','name' => 'تلفزيون', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/televisions.png',],
             ['id' => '180','categories_id' => '2','name' => 'غسالة', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/dishwasher.png',],
             ['id' => '181','categories_id' => '2','name' => 'ثلاجة', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/Refrigerator.png',],
             ['id' => '182','categories_id' => '2','name' => 'عجانة', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/Mixer.png',],
             ['id' => '183','categories_id' => '2','name' => 'فرن الغاز', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/stovegas.png',],
             ['id' => '184','categories_id' => '2','name' => 'ميكرويف', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/Microwave.png',],
             ['id' => '185','categories_id' => '2','name' => 'مكواه', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/steamiron.png',],
             ['id' => '186','categories_id' => '2','name' => 'مروحة', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/Fan.png',],
             ['id' => '187','categories_id' => '2','name' => 'المكيفات', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/evaporative.png',],
             ['id' => '188','categories_id' => '2','name' => 'الخلاط', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/Blender-Mixe.png',],
             ['id' => '189','categories_id' => '2','name' => 'مكنسة كهربائية', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/vacuum-cleaner.png',],
             ['id' => '190','categories_id' => '2','name' => 'الطابعات', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/printer.png',],
             ['id' => '191','categories_id' => '2','name' => 'السماعات', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/headphones.png',],
             ['id' => '192','categories_id' => '2','name' => 'أجهزة طبية', 'category_name' => 'اجهزة','src' => 'storage/subcategory/خدمات/medicaldevices.png',],
             ['id' => '193','categories_id' => '2','name' => 'أجهزة منزلية', 'category_name' => 'اجهزة','src' => 'storage/subcategory/خدمات/appliances.png',],
             ['id' => '194','categories_id' => '2','name' => 'اجهزة اخرى', 'category_name' => 'اجهزة','src' => 'storage/subcategory/اجهزة/appliances.png',],
             ['id' => '195','categories_id' => '1','name' => 'موارد بشرية', 'category_name' => 'وظائف','src' => 'storage/subcategory/وظائف/Humanresources.png',],
             ['id' => '196','categories_id' => '7','name' => 'عاجل', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/uragent.jpg',],
             ['id' => '197','categories_id' => '7','name' => 'غزة', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/gaza.png',],
             ['id' => '198','categories_id' => '7','name' => 'الضفة', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/west_bank.png',],
             ['id' => '199','categories_id' => '7','name' => 'القدس', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/jorasalim.png',],
             ['id' => '200','categories_id' => '7','name' => 'اراضي ال 48', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/land48.png',],
             ['id' => '201','categories_id' => '7','name' => 'في الخارج', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/outside.png',],
             ['id' => '202','categories_id' => '7','name' => 'سياسة', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/politcal.png',],
             ['id' => '203','categories_id' => '7','name' => 'اقتصاد', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/economy.jpg',],
             ['id' => '204','categories_id' => '7','name' => 'اسرائيليات', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/isreal.png',],
             ['id' => '205','categories_id' => '7','name' => 'الصحة', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/Health.png',],
             ['id' => '206','categories_id' => '7','name' => 'التعليم', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/education.png',],
             ['id' => '207','categories_id' => '7','name' => 'التكنولجيا', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/technology.jpg',],
             ['id' => '208','categories_id' => '7','name' => 'محلي', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/breaking.jpg',],
             ['id' => '209','categories_id' => '7','name' => 'عربي', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/arabic.png',],
             ['id' => '210','categories_id' => '7','name' => 'دولي', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/glob.png',],
             ['id' => '211','categories_id' => '7','name' => 'المجتمع', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/society.png',],
             ['id' => '212','categories_id' => '7','name' => 'اعمال وشركات', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/marketing.png',],
             ['id' => '213','categories_id' => '7','name' => 'سفر وسياحة', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/airplane.jpg',],
             ['id' => '214','categories_id' => '7','name' => 'ثقافة وفنون', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/camerapencil.png',],
             ['id' => '215','categories_id' => '7','name' => 'ترفيه', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/celebration.png',],
             ['id' => '216','categories_id' => '7','name' => 'منوعات', 'category_name' => 'اخبار','src' => 'storage/subcategory/اخبار/news.png',],

        ];

        foreach ($subCategories as $subCategory) {
            $subCategoryData = Sub_categories::create([
                'id' => $subCategory['id'],
                'name' => $subCategory['name'],
                'categories_id' =>$subCategory['categories_id'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
            $photo = new Photos([
                'src' => $subCategory['src'],
            ]);
            $subCategoryData->photos()->save($photo);
        }
    }
}
