name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # or main, depending on your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy application files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: talbna.cloud
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Local directory to deploy (excluding the paaublic directory)
          server-dir: /home/u693675641/domains/talbna.cloud  # The folder where the app should reside (non-public folder)

      - name: Deploy public files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: talbna.cloud
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/  # Local directory for public files
          server-dir: /home/u693675641/domains/talbna.cloud/public_html/  # Server path for the public directory
